In [1]:
import pandas as pd

In [2]:
imdb_tmdb = pd.read_csv('../data/imdb_tmdb.csv')

In [3]:
relevant_titles = set(imdb_tmdb['tconst'].values)

In [5]:
name_basics = pd.read_csv('../cleaned_data/relevant_name_basics.txt', sep='|')

In [6]:
crew = pd.read_csv('../cleaned_data/relevant_crew.txt', sep='|')

In [7]:
principals = pd.read_csv('../cleaned_data/relevant_principals.txt', sep='|')

In [8]:
ratings = pd.read_csv('../cleaned_data/relevant_title_ratings.csv')

In [23]:
imdb_tmdb.dtypes

Unnamed: 0                 int64
belongs_to_collection     object
budget                   float64
genres_x                  object
id                       float64
imdb_id                   object
original_language         object
original_title            object
overview                  object
popularity               float64
production_companies      object
production_countries      object
release_date              object
revenue                  float64
runtime                  float64
spoken_languages          object
status                    object
status_code              float64
status_message           float64
tagline                   object
title                     object
vote_average             float64
vote_count               float64
release_year               int64
tconst                    object
titleType                 object
primaryTitle              object
isAdult                    int64
startYear                  int64
runtimeMinutes            object
genres_y                  object
_merge                    object
dtype: object

In [26]:
imdb_tmdb[imdb_tmdb['isAdult'] == True]

Empty DataFrame
Columns: [Unnamed: 0, belongs_to_collection, budget, genres_x, id, imdb_id, original_language, original_title, overview, popularity, production_companies, production_countries, release_date, revenue, runtime, spoken_languages, status, status_code, status_message, tagline, title, vote_average, vote_count, release_year, tconst, titleType, primaryTitle, isAdult, startYear, runtimeMinutes, genres_y, _merge]
Index: []

[0 rows x 32 columns]

In [68]:
imdb_tmdb.iloc[3671]

Unnamed: 0                                                           33003
belongs_to_collection                                                  NaN
budget                                                                 200
genres_x                 [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
id                                                                  222060
imdb_id                                                          tt1988546
original_language                                                       en
original_title                             Anonymous Celebrities: Animatic
overview                 Nerdy Herbert meets Annie, the holier-than-tho...
popularity                                                             0.6
production_companies     [{'id': 16840, 'logo_path': None, 'name': 'Ran...
production_countries                              United States of America
release_date                                                    2005-10-18
revenue                                                                 10
runtime                                                                 99
spoken_languages                  [{'iso_639_1': 'en', 'name': 'English'}]
status                                                            Released
status_code                                                            NaN
status_message                                                         NaN
tagline                  A barely animated sci-fi musical comedy romanc...
title                                      ANONYMOUS CELEBRITIES: ANIMATIC
vote_average                                                            10
vote_count                                                               1
release_year                                                          2005
tconst                                                           tt1988546
titleType                                                            movie
primaryTitle                               ANONYMOUS CELEBRITIES: ANIMATIC
isAdult                                                                  0
startYear                                                             2011
runtimeMinutes                                                          99
genres_y                                                                \N
_merge                                                                both
Name: 3671, dtype: object

In [ ]:
imdb_tmdb['runtime'][-100:-50]

In [33]:
imdb_tmdb.dtypes

Unnamed: 0                 int64
belongs_to_collection     object
budget                   float64
genres_x                  object
id                       float64
imdb_id                   object
original_language         object
original_title            object
overview                  object
popularity               float64
production_companies      object
production_countries      object
release_date              object
revenue                  float64
runtime                  float64
spoken_languages          object
status                    object
status_code              float64
status_message           float64
tagline                   object
title                     object
vote_average             float64
vote_count               float64
release_year               int64
tconst                    object
titleType                 object
primaryTitle              object
isAdult                    int64
startYear                  int64
runtimeMinutes            object
genres_y                  object
_merge                    object
dtype: object

In [112]:
movies_dropped = imdb_tmdb.drop(['belongs_to_collection', 'Unnamed: 0', 'id', 'imdb_id',
               'original_language', 'overview', 'popularity', 'production_countries',
               'release_date', 'spoken_languages', 'status', 'status_code', 'status_message',
               'tagline', 'original_title', 'titleType', 'primaryTitle', 'isAdult',
               'release_year', 'runtime', 'genres_y', '_merge'], axis=1)

In [335]:
num_genres = 4
num_prod_companies = 5
num_directors = 3
num_writers = 5
num_others = 10
num_cast = 10

In [158]:
import json 

def clean_genres(x):
    json_dict = json.loads(x.replace("\'", "\""))
    return [item['name'] for item in json_dict][:num_genres]

def clean_prod_companies(x):
    companies = []
    i = x.find("'name': '")
    while (i != -1):
        companies.append(x[i + len("'name': '"):x.find("', 'origin_country'", i)])
        i = x.find("'name': '", i + 1)
        
    return companies[:num_prod_companies]
#     x_no_single_quotes = x.replace("\'id\'", '\"id\"').replace("\'logo_path\'", '\"logo_path\"').replace("\'origin_country\'", '\"origin_country\"').replace("\'name\'", '\"name\"').replace() 
#     y = x_no_single_quotes.replace(', \"origin_country\": \'\'', "").replace(', \"logo_path\": None', "")
#     print(y)
#     print(y[20:25])
#     json_dict = json.loads(y)
#     return [item['name'] for item in json_dict][:5]


movies_clean_genres = movies_dropped.copy()
movies_clean_genres['genres_x'] = movies_clean_genres['genres_x'].apply(clean_genres)

movie_clean_companies = movies_clean_genres.copy()
movie_clean_companies['production_companies'] = movie_clean_companies['production_companies'].apply(clean_prod_companies)

In [169]:
movies_joined_crew = pd.merge(movie_clean_companies, crew, left_on='tconst', right_on='tconst')

In [170]:
movies_joined_crew

,budget,genres_x,production_companies,revenue,title,vote_average,vote_count,tconst,startYear,runtimeMinutes,directors,writers
0,13000000.0,"[Family, Adventure, Science Fiction]","[Panay Films, Walt Disney Pictures]",45300000.0,EARTH TO ECHO,5.8,394.0,tt2183034,2014,91,nm1757777,"nm2849655,nm0659123"
1,26000000.0,"[Science Fiction, Mystery, Thriller]","[Ram Bergman Productions, Endgame Entertainment]",30523226.0,SELF/LESS,6.3,1929.0,tt2140379,2015,117,nm0802248,"nm1883612,nm0665041"
2,65000000.0,"[Action, Comedy, Crime]","[Chernin Entertainment, Feigco Entertainment, ...",235666219.0,SPY,6.8,4111.0,tt3079380,2015,119,nm0082450,nm0082450
3,5000000.0,"[Action, Drama]",[The Movie Network],1700000.0,BEST OF THE BEST,6.4,93.0,tt0096913,1989,97,nm0705675,"nm0722221,nm0505924,nm0834883"
4,150000.0,"[Horror, Thriller]","[Suited Four Productions, Shooting Creek Films...",560000.0,HOUSE OF GOOD AND EVIL,4.5,23.0,tt1068953,2013,108,nm0612625,nm1846376
...,...,...,...,...,...,...,...,...,...,...,...,...
3737,28000000.0,"[Crime, Drama, Mystery, Thriller]","[Traveling Picture Show Company (TPSC), Jersey...",53181600.0,A WALK AMONG THE TOMBSTONES,6.3,1766.0,tt0365907,2014,114,nm0291082,"nm0088747,nm0291082"
3738,60000000.0,"[Animation, Comedy, Family, Fantasy]",[Laika Entertainment],108255770.0,THE BOXTROLLS,6.6,1085.0,tt0787474,2014,96,"nm0820934,nm0030253","nm0109267,nm1106082,nm2223296,nm0820934,nm0197..."
3739,20000000.0,"[Comedy, Romance, Crime, Drama]","[IAC Films, Ghoulardi Film Company, Warner Bro...",14772346.0,INHERENT VICE,6.6,1476.0,tt1791528,2014,148,nm0000759,"nm0000759,nm1535410"
3740,50000.0,[Crime],[Allied Artists Pictures],600000.0,THE CRY BABY KILLER,5.3,6.0,tt0051500,1958,70,nm0011727,"nm0330388,nm0506544"
3741,103000000.0,"[Adventure, Comedy, Family, Animation]","[Blue Sky Studios, 20th Century Fox Animation,...",500188435.0,RIO 2,6.3,1949.0,tt2357291,2014,101,nm0757858,"nm0722610,nm6423183,nm0081081,nm3229505,nm0757..."

In [178]:
principals_no_job_chars = principals.drop(['characters', 'job'], axis = 1)

In [179]:
principals_no_job_chars

          tconst  ordering     nconst         category
0      tt2183034        10  nm1131817  cinematographer
1      tt2183034         1  nm5128387            actor
2      tt2183034         2  nm4702342            actor
3      tt2183034         3  nm3419119            actor
4      tt2183034         4  nm4125403          actress
...          ...       ...        ...              ...
37253  tt2357291         5  nm0757858         director
37254  tt2357291         6  nm0722610           writer
37255  tt2357291         7  nm6423183           writer
37256  tt2357291         8  nm0081081           writer
37257  tt2357291         9  nm3229505           writer

[37258 rows x 4 columns]

In [234]:
# want to capture Robert Downey Jr. in Avengers but non random maintenance guy actor nm3912910
relevant_principals = set(principals_no_job_chars['nconst'].values)

In [235]:
len(list(relevant_principals))

16432

In [236]:
%%time
principals_name_basics = principals_no_job_chars.copy()

cnt = 0 

new_rows = []

for index, row in name_basics.iterrows():
    cnt += 1
    if cnt % 10000 == 0:
        print(cnt)
#         break

    if row['nconst'] not in relevant_principals:
        continue

    if not isinstance(row['knownForTitles'], str):
        continue
    
    
    titles = row['knownForTitles'].split(',')
    primaryProfession = row['primaryProfession'].split(',')
    isActor = primaryProfession[0] == 'actor' or primaryProfession[0] == 'actress'
    
    for t in titles:
        new_rows.append(pd.Series([t, 11, row['nconst'], primaryProfession[0]], index=principals_name_basics.columns))

10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000
270000
280000
290000
300000
310000
320000
330000
340000
350000
360000
370000
380000
390000
CPU times: user 53.8 s, sys: 50 ms, total: 53.8 s
Wall time: 53.8 s

In [237]:
len(new_rows)

26889

In [238]:
%%time
principals_name_basics = principals_name_basics.append(new_rows, ignore_index=True)

CPU times: user 1.51 s, sys: 0 ns, total: 1.51 s
Wall time: 1.51 s

Avengers movie before getting new information

In [250]:
avengers_filter = (principals_no_job_chars['tconst'] == 'tt0848228') & ((principals_no_job_chars['category'] == 'actor') | (principals_no_job_chars['category'] == 'actress'))

principals_no_job_chars[avengers_filter]

          tconst  ordering     nconst category
33306  tt0848228         1  nm0000375    actor
33307  tt0848228         2  nm0262635    actor
33308  tt0848228         3  nm0424060  actress
33309  tt0848228         4  nm0719637    actor

Avengers movie after getting new Information (also captures Cobie Smulders and Tom Hiddleston)

In [253]:
avengers_filter = (principals_name_basics['tconst'] == 'tt0848228') & ((principals_name_basics['category'] == 'actor') | (principals_name_basics['category'] == 'actress'))

principals_name_basics[avengers_filter].drop_duplicates(subset=['nconst'])

          tconst  ordering     nconst category
33306  tt0848228         1  nm0000375    actor
33307  tt0848228         2  nm0262635    actor
33308  tt0848228         3  nm0424060  actress
33309  tt0848228         4  nm0719637    actor
58840  tt0848228        11  nm1089991    actor
58979  tt0848228        11  nm1130627  actress

In [254]:
principals_name_basics_sorted = principals_name_basics.sort_values(['tconst', 'ordering'])

In [259]:
principals_name_basics_no_dups = principals_name_basics_sorted.drop_duplicates(['tconst', 'nconst'])

In [271]:
principals_name_basics_no_dups

           tconst  ordering     nconst         category
47448   tt0016884        11  nm0318105            actor
45490   tt0020332        11  nm0199841          actress
42430   tt0020629        11  nm0027173           writer
46214   tt0020629        11  nm0249186  cinematographer
40638   tt0021749        11  nm0003424            actor
...           ...       ...        ...              ...
27995   tt9015178         6  nm0619069           writer
27996   tt9015178         7  nm0849083           writer
27997   tt9015178         8  nm0370651         producer
27998   tt9015178         9  nm0437132         producer
27989   tt9015178        10  nm0466544         composer

[53994 rows x 4 columns]

In [270]:
principals_name_basics_no_dups.to_csv('../cleaned_data/all_principals.csv')

In [277]:
principals_writers = principals_name_basics_no_dups[(principals_name_basics_no_dups['category'] == 'writer')]

In [275]:
principals_directors = principals_name_basics_no_dups[(principals_name_basics_no_dups['category'] == 'director')]

In [278]:
principals_writers

           tconst  ordering     nconst category
42430   tt0020629        11  nm0027173   writer
42793   tt0021884        11  nm0049721   writer
55510   tt0021884        11  nm0791217   writer
54835   tt0024894        11  nm0750538   writer
37447   tt0027977        11  nm0000122   writer
...           ...       ...        ...      ...
4712    tt7958736         6  nm3398282   writer
4876    tt8085790         6  nm2002824   writer
4779    tt8155288         6  nm1245146   writer
27995   tt9015178         6  nm0619069   writer
27996   tt9015178         7  nm0849083   writer

[8853 rows x 4 columns]

In [279]:
principals_directors

           tconst  ordering     nconst  category
51068   tt0023876        11  nm0515979  director
38924   tt0025316        11  nm0001008  director
42555   tt0029583        11  nm0035899  director
49242   tt0029583        11  nm0414144  director
40301   tt0029843        11  nm0002031  director
...           ...       ...        ...       ...
4711    tt7958736         5  nm0853238  director
4875    tt8085790         5  nm1202276  director
4778    tt8155288         5  nm0484907  director
4885    tt8772262         5  nm4170048  director
27994   tt9015178         5  nm0368057  director

[4411 rows x 4 columns]

In [280]:
crew_merged_principals = crew.copy()

for index, row in crew_merged_principals.iterrows():
    directors = row['directors'].split(',')
    writers = row['directors'].split(',')
    
    cur_principals_writers = principals_writers[principals_writers['tconst'] == row['tconst']]['nconst'].values
    cur_principals_directors = principals_directors[principals_directors['tconst'] == row['tconst']]['nconst'].values

    writers = list(set(writers).union(set(cur_principals_writers)))
    directors = list(set(directors).union(set(cur_principals_directors)))
    
    row['directors'] = directors
    row['writers'] = writers

Sherlock Holmes 2 incomplete crew

In [293]:
crew[crew['tconst'] == 'tt1515091']

         tconst  directors                        writers
1705  tt1515091  nm0005363  nm1802251,nm0612487,nm0236279

Sherlock Holmes 2 full crew

In [291]:
crew_merged_principals[crew_merged_principals['tconst'] == 'tt1515091']

         tconst    directors                                       writers
1705  tt1515091  [nm0005363]  [nm1802251, nm0612487, nm0236279, nm0005363]

In [301]:
principals_name_basics_cast = principals_name_basics_no_dups[(principals_name_basics_no_dups['category'] == 'actor')
                                                                | (principals_name_basics_no_dups['category'] == 'actress')]

In [302]:
principals_name_basics_other = \
principals_name_basics_no_dups[(principals_name_basics_no_dups['category'] != 'actor')
                                & (principals_name_basics_no_dups['category'] != 'actress')
                                & (principals_name_basics_no_dups['category'] != 'writer')
                                & (principals_name_basics_no_dups['category'] != 'director')]

In [314]:
%%time
cast_rows = []

for title in relevant_titles:
    cur_cast = principals_name_basics_cast[principals_name_basics_cast['tconst'] == title]['nconst'].values
    cast_rows.append([title, list(cur_cast)])

CPU times: user 8.27 s, sys: 7.76 ms, total: 8.28 s
Wall time: 8.28 s

In [317]:
%%time
cast_df = pd.DataFrame(cast_rows, columns=['tconst', 'cast'])

CPU times: user 2.32 ms, sys: 27 Âµs, total: 2.35 ms
Wall time: 1.99 ms

In [326]:
cast_df

         tconst                                               cast
0     tt1498569       [nm1985859, nm1375330, nm1076976, nm0004922]
1     tt0080761       [nm0658133, nm0454415, nm0852551, nm0604987]
2     tt0072737       [nm0000314, nm0000380, nm0409866, nm0001642]
3     tt0048960       [nm0000057, nm0134594, nm0000511, nm0628579]
4     tt0799934  [nm0085312, nm0080049, nm0000418, nm0001201, n...
...         ...                                                ...
3749  tt0046912       [nm0001537, nm0000038, nm0191950, nm0002369]
3750  tt0892318       [nm1086543, nm0305558, nm0000603, nm0213482]
3751  tt0091613       [nm0522440, nm0000369, nm0001527, nm0656183]
3752  tt0095270       [nm0095122, nm0114616, nm0001145, nm0001323]
3753  tt0452624       [nm0000123, nm0000949, nm0001497, nm0000977]

[3754 rows x 2 columns]

In [321]:
cast_df[cast_df['tconst'] == 'tt0848228']['cast'].values

array([list(['nm0000375', 'nm0262635', 'nm0424060', 'nm0719637', 'nm1089991', 'nm1130627'])],
      dtype=object)

In [322]:
%%time
other_rows = []

for title in relevant_titles:
    cur_others = principals_name_basics_other[principals_name_basics_other['tconst'] == title]['nconst'].values
    other_rows.append([title, list(cur_others)])

CPU times: user 7.59 s, sys: 31.8 ms, total: 7.63 s
Wall time: 7.62 s

In [323]:
%%time
other_df = pd.DataFrame(other_rows, columns=['tconst', 'others'])

CPU times: user 2.16 ms, sys: 0 ns, total: 2.16 ms
Wall time: 1.94 ms

In [325]:
other_df[other_df['tconst'] == 'tt0848228']['others'].values

array([list(['nm0270559', 'nm0006293', 'nm0568974', 'nm0285701', 'nm0009540', 'nm0489809', 'nm2000224'])],
      dtype=object)

In [327]:
other_df

         tconst                                             others
0     tt1498569       [nm0004976, nm0397171, nm0000165, nm2833364]
1     tt0080761                  [nm0006185, nm0009161, nm0292711]
2     tt0072737                                                 []
3     tt0048960                             [nm0865239, nm0512068]
4     tt0799934  [nm1028107, nm0284577, nm0076259, nm0475578, n...
...         ...                                                ...
3749  tt0046912                  [nm0006323, nm0122079, nm0270458]
3750  tt0892318                  [nm0000289, nm0004799, nm0438210]
3751  tt0091613                  [nm0798680, nm0610781, nm0123394]
3752  tt0095270  [nm0003080, nm0888536, nm0409392, nm0359000, n...
3753  tt0452624                  [nm0963211, nm0414423, nm0002353]

[3754 rows x 2 columns]

In [332]:
merged_crew = pd.merge(movie_clean_companies, crew_merged_principals,
                          left_on=['tconst'], right_on=['tconst'])

merged_cast = pd.merge(merged_crew, cast_df,
                          left_on=['tconst'], right_on=['tconst'])

merged_others = pd.merge(merged_cast, other_df,
                          left_on=['tconst'], right_on=['tconst'])

In [333]:
merged_others

,budget,genres_x,production_companies,revenue,title,vote_average,vote_count,tconst,startYear,runtimeMinutes,directors,writers,cast,others
0,13000000.0,"[Family, Adventure, Science Fiction]","[Panay Films, Walt Disney Pictures]",45300000.0,EARTH TO ECHO,5.8,394.0,tt2183034,2014,91,[nm1757777],"[nm0659123, nm2849655, nm1757777]","[nm5128387, nm4702342, nm3419119, nm4125403, n...","[nm1448916, nm2468967, nm1131817]"
1,26000000.0,"[Science Fiction, Mystery, Thriller]","[Ram Bergman Productions, Endgame Entertainment]",30523226.0,SELF/LESS,6.3,1929.0,tt2140379,2015,117,[nm0802248],"[nm1883612, nm0802248, nm0665041]","[nm0005351, nm2358540, nm0328828, nm0001426]","[nm0074851, nm0772283, nm0827726]"
2,65000000.0,"[Action, Comedy, Crime]","[Chernin Entertainment, Feigco Entertainment, ...",235666219.0,SPY,6.8,4111.0,tt3079380,2015,119,[nm0082450],[nm0082450],"[nm0565250, nm0126284, nm0000179, nm0005458]","[nm1858656, nm2295810, nm0867768, nm0788640, n..."
3,5000000.0,"[Action, Drama]",[The Movie Network],1700000.0,BEST OF THE BEST,6.4,93.0,tt0096913,1989,97,[nm0705675],"[nm0705675, nm0834883, nm0505924]","[nm0000616, nm0000469, nm0000476, nm0722221, n...","[nm0833857, nm0319457, nm0752519]"
4,150000.0,"[Horror, Thriller]","[Suited Four Productions, Shooting Creek Films...",560000.0,HOUSE OF GOOD AND EVIL,4.5,23.0,tt1068953,2013,108,[nm0612625],"[nm1846376, nm0612625]","[nm4112571, nm0646792, nm0547174, nm0722468]","[nm1252996, nm3337885, nm2044090, nm3752407]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3737,28000000.0,"[Crime, Drama, Mystery, Thriller]","[Traveling Picture Show Company (TPSC), Jersey...",53181600.0,A WALK AMONG THE TOMBSTONES,6.3,1766.0,tt0365907,2014,114,[nm0291082],"[nm0291082, nm0088747]","[nm0000553, nm1405398, nm1092086, nm2933542, n...","[nm1180690, nm0000362, nm1003922, nm0787834, n..."
3738,60000000.0,"[Animation, Comedy, Family, Fantasy]",[Laika Entertainment],108255770.0,THE BOXTROLLS,6.6,1085.0,tt0787474,2014,96,"[nm0030253, nm0820934]","[nm0030253, nm0109267, nm1106082, nm2223296, n...","[nm0001426, nm0364813, nm0296545, nm1547964]",[]
3739,20000000.0,"[Comedy, Romance, Crime, Drama]","[IAC Films, Ghoulardi Film Company, Warner Bro...",14772346.0,INHERENT VICE,6.6,1476.0,tt1791528,2014,148,[nm0000759],"[nm1535410, nm0000759]","[nm0001618, nm0000982, nm0005562, nm2239702, n...","[nm0526917, nm0783280, nm0339351, nm0005696]"
3740,50000.0,[Crime],[Allied Artists Pictures],600000.0,THE CRY BABY KILLER,5.3,6.0,tt0051500,1958,70,[nm0011727],"[nm0011727, nm0506544, nm0330388]","[nm0491591, nm0000197, nm0593198, nm0357020]","[nm0469436, nm0545289, nm0006086]"
3741,103000000.0,"[Adventure, Comedy, Family, Animation]","[Blue Sky Studios, 20th Century Fox Animation,...",500188435.0,RIO 2,6.3,1949.0,tt2357291,2014,101,[nm0757858],"[nm3229505, nm0081081, nm0185934, nm0722610, n...","[nm0251986, nm0004266, nm1318596, nm0000412]",[nm1512524]

In [340]:
genres_cols = ['genre_' + str(x + 1) for x in range(num_genres)]
print(genres_cols)

prod_companies_cols = ['prod_company_' + str(x + 1) for x in range(num_prod_companies)]
print(prod_companies_cols)    

writers_cols = ['writer_' + str(x + 1) for x in range(num_writers)]
print(writers_cols)   

directors_cols = ['director_' + str(x + 1) for x in range(num_directors)]
print(directors_cols)   

cast_cols = ['cast_' + str(x + 1) for x in range(num_cast)]
print(cast_cols)   

others_cols = ['others_' + str(x + 1) for x in range(num_others)]
print(others_cols)

def select_attribute(x, i):
    if i < len(x):
        return x[i]
    return ''

everything_merged = merged_others.copy()

for i in range(num_genres):
    col = genres_cols[i]
    everything_merged[col] = movies_list_to_cols['genres_x'].apply(lambda x : select_attribute(x, i))
    
for i in range(num_prod_companies):
    col = prod_companies_cols[i]
    everything_merged[col] = movies_list_to_cols['production_companies'].apply(lambda x : select_attribute(x, i))
    
for i in range(num_writers):
    col = writers_cols[i]
    everything_merged[col] = movies_list_to_cols['writers'].apply(lambda x : select_attribute(x, i))
    
for i in range(num_directors):
    col = directors_cols[i]
    everything_merged[col] = movies_list_to_cols['directors'].apply(lambda x : select_attribute(x, i))
        
for i in range(num_cast):
    col = cast_cols[i]
    everything_merged[col] = movies_list_to_cols['cast'].apply(lambda x : select_attribute(x, i))
        
for i in range(num_others):
    col = others_cols[i]
    everything_merged[col] = movies_list_to_cols['others'].apply(lambda x : select_attribute(x, i))

['genre_1', 'genre_2', 'genre_3', 'genre_4']
['prod_company_1', 'prod_company_2', 'prod_company_3', 'prod_company_4', 'prod_company_5']
['writer_1', 'writer_2', 'writer_3', 'writer_4', 'writer_5']
['director_1', 'director_2', 'director_3']
['cast_1', 'cast_2', 'cast_3', 'cast_4', 'cast_5', 'cast_6', 'cast_7', 'cast_8', 'cast_9', 'cast_10']
['others_1', 'others_2', 'others_3', 'others_4', 'others_5', 'others_6', 'others_7', 'others_8', 'others_9', 'others_10']

In [139]:
pd.set_option('display.max_rows', 100)

In [117]:
pd.set_option('display.max_columns', 500)

In [343]:
everything_merged[everything_merged['tconst']=='tt0848228']

,budget,genres_x,production_companies,revenue,title,vote_average,vote_count,tconst,startYear,runtimeMinutes,directors,writers,cast,others,genre_1,genre_2,genre_3,genre_4,prod_company_1,prod_company_2,prod_company_3,prod_company_4,prod_company_5,writer_1,writer_2,writer_3,writer_4,writer_5,director_1,director_2,director_3,cast_1,cast_2,cast_3,cast_4,cast_5,cast_6,cast_7,cast_8,cast_9,cast_10,others_1,others_2,others_3,others_4,others_5,others_6,others_7,others_8,others_9,others_10
3344,220000000.0,"[Science Fiction, Action, Adventure]",[Marvel Studios],1.519558e+09,THE AVENGERS,7.7,20827.0,tt0848228,2012,143,[nm0923736],"[nm0672015, nm0923736]","[nm0000375, nm0262635, nm0424060, nm0719637, n...","[nm0270559, nm0006293, nm0568974, nm0285701, n...",Science Fiction,Action,Adventure,,Marvel Studios,,,,,nm0672015,nm0923736,,,,nm0923736,,,nm0000375,nm0262635,nm0424060,nm0719637,nm1089991,nm1130627,,,,,nm0270559,nm0006293,nm0568974,nm0285701,nm0009540,nm0489809,nm2000224,,,

In [350]:
everything_merged_no_dup_cols = everything_merged.drop(['genres_x', 'production_companies', 'writers',
                                                        'directors', 'cast', 'others'], axis=1)

In [352]:
everything_merged_no_dup_cols.to_csv('../cleaned_data/everything_merged.csv')

In [368]:
movies_by_year = everything_merged_no_dup_cols.sort_values(['startYear'])

In [369]:
movies_by_year

,budget,revenue,title,vote_average,vote_count,tconst,startYear,runtimeMinutes,genre_1,genre_2,genre_3,genre_4,prod_company_1,prod_company_2,prod_company_3,prod_company_4,prod_company_5,writer_1,writer_2,writer_3,writer_4,writer_5,director_1,director_2,director_3,cast_1,cast_2,cast_3,cast_4,cast_5,cast_6,cast_7,cast_8,cast_9,cast_10,others_1,others_2,others_3,others_4,others_5,others_6,others_7,others_8,others_9,others_10
445,16988.0,87028.0,THE ROSE OF THE RANCHO,0.0,0.0,tt0004545,1914,\N,Romance,Western,Adventure,,Jesse L. Lasky Feature Play Company,,,,,nm0001124,nm0876445,nm0067584,,,nm0001124,,,nm0057585,nm0002034,nm0478890,nm0426668,,,,,,,nm0005931,,,,,,,,,
3072,100000.0,11000000.0,THE BIRTH OF A NATION,6.5,234.0,tt0004972,1915,195,Drama,History,War,,Epoch Film Co.,,,,,nm0228746,nm0000428,nm0940488,,,nm0000428,,,nm0001273,nm0550615,nm0910400,nm0178270,,,,,,,nm0106922,nm0005658,nm0376221,,,,,,,
353,15110.0,102224.0,THE GIRL OF THE GOLDEN WEST,5.5,2.0,tt0005393,1915,50,Western,Romance,,,Jesse L. Lasky Feature Play Company,,,,,nm0001124,nm0067584,,,,nm0001124,,,nm0885818,nm0731623,nm0676473,nm0454458,,,,,,,nm0005931,nm0371277,,,,,,,,
103,1000000.0,1390000.0,A DAUGHTER OF THE GODS,5.0,1.0,tt0006568,1916,180,Fantasy,Drama,,,Fox Film Corporation,,,,,nm0107543,nm5921220,,,,nm0107543,,,nm0445807,nm0790137,nm0208415,nm0393411,,,,,,,nm1135428,nm0005646,nm0191667,nm0402478,,,,,,
1668,250000.0,8000000.0,MICKEY,7.0,8.0,tt0009369,1918,93,Comedy,Drama,,,Mabel Normand Feature Film Company,,,,,nm0949648,nm0428059,nm0215874,nm0370271,,nm0949648,nm0428059,,nm0635667,nm0629589,nm0479126,nm0168595,,,,,,,nm0784407,nm0413164,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,200000000.0,245000000.0,DARK PHOENIX,6.1,2458.0,tt6565702,2019,113,Science Fiction,Action,Adventure,,20th Century Fox,Genre Films,Bad Hat Harry Productions,Marvel Entertainment,Kinberg Genre,nm0126208,nm1334526,nm1079211,nm1079208,nm0456158,nm1334526,,,nm0564215,nm1055413,nm2225369,nm0396558,nm0791864,nm1404239,nm5557932,,,,nm2385360,nm3767676,,,,,,,,
480,6000000.0,22220378.0,BOOKSMART,7.2,634.0,tt1489887,2019,102,Comedy,,,,Annapurna Pictures,Gary Sanchez Productions,,,,nm1312575,nm4199289,nm2573005,nm2873539,nm1054604,nm1312575,,,nm3239803,nm2788156,nm1790970,nm0837177,nm1094137,nm9537602,,,,,nm2273482,nm1819990,,,,,,,,
482,9000000.0,25327500.0,HAPPY DEATH DAY 2U,6.2,1429.0,tt8155288,2019,100,Horror,Mystery,Thriller,Science Fiction,Digital Riot Media,Blumhouse Productions,,,,nm0484907,nm1245146,,,,nm0484907,,,nm1557329,nm3441152,nm7059572,nm4139037,,,,,,,nm0089658,nm0566970,nm0002947,nm3015807,,,,,,
162,175000000.0,519802847.0,TOY STORY 4,7.6,3038.0,tt1979376,2019,100,Adventure,Animation,Comedy,Family,Walt Disney Pictures,Pixar,,,,nm2155757,nm1445746,nm0566489,nm0429069,nm0004056,nm2155757,,,nm0000158,nm0000741,nm0001633,nm0355024,,,,,,,,,,,,,,,,
361,80000000.0,155152550.0,THE SECRET LIFE OF PETS 2,6.6,822.0,tt5113040,2019,86,Adventure,Animation,Comedy,Family,Universal Pictures,Illumination Entertainment,,,,nm0528244,nm3646390,nm0719208,,,nm3646390,nm0719208,,nm0652663,nm0366389,nm0000148,nm0832314,,,,,,,nm0372329,nm0577560,nm0006035,,,,,,,

In [358]:
!pip3 install cpi --user

Collecting cpi
  Using cached https://files.pythonhosted.org/packages/ca/d1/04e0555d127270aeff9cda013dda91b94e4b968907386997018c3d7eb167/cpi-0.1.15-py2.py3-none-any.whl
Requirement already satisfied: pandas>=0.23.1 in /home/trb116/.local/lib/python3.7/site-packages (from cpi) (0.25.2)
Requirement already satisfied: requests>=2.20.0 in /home/trb116/.local/lib/python3.7/site-packages (from cpi) (2.22.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/trb116/.local/lib/python3.7/site-packages (from cpi) (2.8.0)
Collecting click>=6.7
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Requirement already satisfied: pytz>=2017.2 in /home/trb116/.local/lib/python3.7/site-packages (from pandas>=0.23.1->cpi) (2019.3)
Requirement already satisfied: numpy>=1.13.3 in /home/trb116/.local/lib/python3.7/site-packages (from pandas>=0.23.1->cpi) (1.17.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/trb116/.local/lib/python3.7/site-packages (from requests>=2.20.0->cpi) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /home/trb116/.local/lib/python3.7/site-packages (from requests>=2.20.0->cpi) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/trb116/.local/lib/python3.7/site-packages (from requests>=2.20.0->cpi) (1.25.6)
Requirement already satisfied: certifi>=2017.4.17 in /home/trb116/.local/lib/python3.7/site-packages (from requests>=2.20.0->cpi) (2019.9.11)
Requirement already satisfied: six>=1.5 in /home/trb116/.local/lib/python3.7/site-packages (from python-dateutil>=2.7.3->cpi) (1.12.0)
Installing collected packages: click, cpi
Successfully installed click-7.0 cpi-0.1.15

In [361]:
import cpi

/home/trb116/.local/lib/python3.7/site-packages/cpi/__init__.py:46: StaleDataWarning: CPI data is out of date. To accurately inflate to today's dollars, you must run `cpi.update()`.
  warnings.warn(StaleDataWarning())

In [362]:
cpi.inflate(100, 1950)

1041.9377593360996

In [380]:
movies_no_inflation = movies_by_year.copy()

for index, row in movies_no_inflation.iterrows():
    year = row['startYear']
    if year != 2019:
        movies_no_inflation.set_value(index, 'budget', cpi.inflate(row['budget'], year))
        movies_no_inflation.set_value(index, 'revenue', cpi.inflate(row['revenue'], year))

/home/trb116/.local/lib/python3.7/site-packages/ipykernel_launcher.py:6: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

/home/trb116/.local/lib/python3.7/site-packages/ipykernel_launcher.py:7: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  import sys

In [383]:
movies_by_year[movies_by_year['tconst'] == 'tt0848228']

,budget,revenue,title,vote_average,vote_count,tconst,startYear,runtimeMinutes,genre_1,genre_2,genre_3,genre_4,prod_company_1,prod_company_2,prod_company_3,prod_company_4,prod_company_5,writer_1,writer_2,writer_3,writer_4,writer_5,director_1,director_2,director_3,cast_1,cast_2,cast_3,cast_4,cast_5,cast_6,cast_7,cast_8,cast_9,cast_10,others_1,others_2,others_3,others_4,others_5,others_6,others_7,others_8,others_9,others_10
3344,220000000.0,1.519558e+09,THE AVENGERS,7.7,20827.0,tt0848228,2012,143,Science Fiction,Action,Adventure,,Marvel Studios,,,,,nm0672015,nm0923736,,,,nm0923736,,,nm0000375,nm0262635,nm0424060,nm0719637,nm1089991,nm1130627,,,,,nm0270559,nm0006293,nm0568974,nm0285701,nm0009540,nm0489809,nm2000224,,,

In [384]:
movies_no_inflation[movies_no_inflation['tconst'] == 'tt0848228']

,budget,revenue,title,vote_average,vote_count,tconst,startYear,runtimeMinutes,genre_1,genre_2,genre_3,genre_4,prod_company_1,prod_company_2,prod_company_3,prod_company_4,prod_company_5,writer_1,writer_2,writer_3,writer_4,writer_5,director_1,director_2,director_3,cast_1,cast_2,cast_3,cast_4,cast_5,cast_6,cast_7,cast_8,cast_9,cast_10,others_1,others_2,others_3,others_4,others_5,others_6,others_7,others_8,others_9,others_10
3344,2.406140e+08,1.661941e+09,THE AVENGERS,7.7,20827.0,tt0848228,2012,143,Science Fiction,Action,Adventure,,Marvel Studios,,,,,nm0672015,nm0923736,,,,nm0923736,,,nm0000375,nm0262635,nm0424060,nm0719637,nm1089991,nm1130627,,,,,nm0270559,nm0006293,nm0568974,nm0285701,nm0009540,nm0489809,nm2000224,,,

In [385]:
movies_no_inflation

,budget,revenue,title,vote_average,vote_count,tconst,startYear,runtimeMinutes,genre_1,genre_2,genre_3,genre_4,prod_company_1,prod_company_2,prod_company_3,prod_company_4,prod_company_5,writer_1,writer_2,writer_3,writer_4,writer_5,director_1,director_2,director_3,cast_1,cast_2,cast_3,cast_4,cast_5,cast_6,cast_7,cast_8,cast_9,cast_10,others_1,others_2,others_3,others_4,others_5,others_6,others_7,others_8,others_9,others_10
445,4.265806e+05,2.185334e+06,THE ROSE OF THE RANCHO,0.0,0.0,tt0004545,1914,\N,Romance,Western,Adventure,,Jesse L. Lasky Feature Play Company,,,,,nm0001124,nm0876445,nm0067584,,,nm0001124,,,nm0057585,nm0002034,nm0478890,nm0426668,,,,,,,nm0005931,,,,,,,,,
3072,2.486208e+06,2.734829e+08,THE BIRTH OF A NATION,6.5,234.0,tt0004972,1915,195,Drama,History,War,,Epoch Film Co.,,,,,nm0228746,nm0000428,nm0940488,,,nm0000428,,,nm0001273,nm0550615,nm0910400,nm0178270,,,,,,,nm0106922,nm0005658,nm0376221,,,,,,,
353,3.756660e+05,2.541501e+06,THE GIRL OF THE GOLDEN WEST,5.5,2.0,tt0005393,1915,50,Western,Romance,,,Jesse L. Lasky Feature Play Company,,,,,nm0001124,nm0067584,,,,nm0001124,,,nm0885818,nm0731623,nm0676473,nm0454458,,,,,,,nm0005931,nm0371277,,,,,,,,
103,2.303734e+07,3.202190e+07,A DAUGHTER OF THE GODS,5.0,1.0,tt0006568,1916,180,Fantasy,Drama,,,Fox Film Corporation,,,,,nm0107543,nm5921220,,,,nm0107543,,,nm0445807,nm0790137,nm0208415,nm0393411,,,,,,,nm1135428,nm0005646,nm0191667,nm0402478,,,,,,
1668,4.157401e+06,1.330368e+08,MICKEY,7.0,8.0,tt0009369,1918,93,Comedy,Drama,,,Mabel Normand Feature Film Company,,,,,nm0949648,nm0428059,nm0215874,nm0370271,,nm0949648,nm0428059,,nm0635667,nm0629589,nm0479126,nm0168595,,,,,,,nm0784407,nm0413164,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,2.000000e+08,2.450000e+08,DARK PHOENIX,6.1,2458.0,tt6565702,2019,113,Science Fiction,Action,Adventure,,20th Century Fox,Genre Films,Bad Hat Harry Productions,Marvel Entertainment,Kinberg Genre,nm0126208,nm1334526,nm1079211,nm1079208,nm0456158,nm1334526,,,nm0564215,nm1055413,nm2225369,nm0396558,nm0791864,nm1404239,nm5557932,,,,nm2385360,nm3767676,,,,,,,,
480,6.000000e+06,2.222038e+07,BOOKSMART,7.2,634.0,tt1489887,2019,102,Comedy,,,,Annapurna Pictures,Gary Sanchez Productions,,,,nm1312575,nm4199289,nm2573005,nm2873539,nm1054604,nm1312575,,,nm3239803,nm2788156,nm1790970,nm0837177,nm1094137,nm9537602,,,,,nm2273482,nm1819990,,,,,,,,
482,9.000000e+06,2.532750e+07,HAPPY DEATH DAY 2U,6.2,1429.0,tt8155288,2019,100,Horror,Mystery,Thriller,Science Fiction,Digital Riot Media,Blumhouse Productions,,,,nm0484907,nm1245146,,,,nm0484907,,,nm1557329,nm3441152,nm7059572,nm4139037,,,,,,,nm0089658,nm0566970,nm0002947,nm3015807,,,,,,
162,1.750000e+08,5.198028e+08,TOY STORY 4,7.6,3038.0,tt1979376,2019,100,Adventure,Animation,Comedy,Family,Walt Disney Pictures,Pixar,,,,nm2155757,nm1445746,nm0566489,nm0429069,nm0004056,nm2155757,,,nm0000158,nm0000741,nm0001633,nm0355024,,,,,,,,,,,,,,,,
361,8.000000e+07,1.551526e+08,THE SECRET LIFE OF PETS 2,6.6,822.0,tt5113040,2019,86,Adventure,Animation,Comedy,Family,Universal Pictures,Illumination Entertainment,,,,nm0528244,nm3646390,nm0719208,,,nm3646390,nm0719208,,nm0652663,nm0366389,nm0000148,nm0832314,,,,,,,nm0372329,nm0577560,nm0006035,,,,,,,

In [387]:
movies_profit = movies_no_inflation.copy()
movies_profit['profit'] = movies_profit['revenue'] - movies_profit['budget']

In [392]:
# movie that tanked the worst
movies_profit.sort_values('profit').iloc[0]

budget                               2.74867e+08
revenue                              9.62466e+07
title                            THE LONE RANGER
vote_average                                   6
vote_count                                  3980
tconst                                 tt1210819
startYear                                   2013
runtimeMinutes                               150
genre_1                                   Action
genre_2                                Adventure
genre_3                                  Western
genre_4
prod_company_1    Silver Bullet Productions (II)
prod_company_2              Walt Disney Pictures
prod_company_3           Jerry Bruckheimer Films
prod_company_4            Blind Wink Productions
prod_company_5                   Infinitum Nihil
writer_1                               nm0254645
writer_2                               nm0893659
writer_3                               nm0744429
writer_4                               nm1244808
writer_5
director_1                             nm0893659
director_2
director_3
cast_1                                 nm0000136
cast_2                                 nm2309517
cast_3                                 nm0001209
cast_4                                 nm0929489
cast_5                                 nm0094495
cast_6                                 nm0339159
cast_7                                 nm1151899
cast_8                                 nm1370408
cast_9                                 nm2016685
cast_10
others_1                               nm0000988
others_2                               nm0001877
others_3                               nm0005648
others_4                               nm0257259
others_5                               nm1913201
others_6
others_7
others_8
others_9
others_10
profit                              -1.78621e+08
Name: 1695, dtype: object

In [394]:
movies_rev_budget_ratio = movies_profit.copy()
movies_rev_budget_ratio['rev_budget_ratio'] = movies_rev_budget_ratio['revenue'] / movies_rev_budget_ratio['budget']

In [395]:
movies_rev_budget_ratio

,budget,revenue,title,vote_average,vote_count,tconst,startYear,runtimeMinutes,genre_1,genre_2,genre_3,genre_4,prod_company_1,prod_company_2,prod_company_3,prod_company_4,prod_company_5,writer_1,writer_2,writer_3,writer_4,writer_5,director_1,director_2,director_3,cast_1,cast_2,cast_3,cast_4,cast_5,cast_6,cast_7,cast_8,cast_9,cast_10,others_1,others_2,others_3,others_4,others_5,others_6,others_7,others_8,others_9,others_10,profit,rev_budget_ratio
445,4.265806e+05,2.185334e+06,THE ROSE OF THE RANCHO,0.0,0.0,tt0004545,1914,\N,Romance,Western,Adventure,,Jesse L. Lasky Feature Play Company,,,,,nm0001124,nm0876445,nm0067584,,,nm0001124,,,nm0057585,nm0002034,nm0478890,nm0426668,,,,,,,nm0005931,,,,,,,,,,1.758753e+06,5.122910
3072,2.486208e+06,2.734829e+08,THE BIRTH OF A NATION,6.5,234.0,tt0004972,1915,195,Drama,History,War,,Epoch Film Co.,,,,,nm0228746,nm0000428,nm0940488,,,nm0000428,,,nm0001273,nm0550615,nm0910400,nm0178270,,,,,,,nm0106922,nm0005658,nm0376221,,,,,,,,2.709967e+08,110.000000
353,3.756660e+05,2.541501e+06,THE GIRL OF THE GOLDEN WEST,5.5,2.0,tt0005393,1915,50,Western,Romance,,,Jesse L. Lasky Feature Play Company,,,,,nm0001124,nm0067584,,,,nm0001124,,,nm0885818,nm0731623,nm0676473,nm0454458,,,,,,,nm0005931,nm0371277,,,,,,,,,2.165835e+06,6.765321
103,2.303734e+07,3.202190e+07,A DAUGHTER OF THE GODS,5.0,1.0,tt0006568,1916,180,Fantasy,Drama,,,Fox Film Corporation,,,,,nm0107543,nm5921220,,,,nm0107543,,,nm0445807,nm0790137,nm0208415,nm0393411,,,,,,,nm1135428,nm0005646,nm0191667,nm0402478,,,,,,,8.984562e+06,1.390000
1668,4.157401e+06,1.330368e+08,MICKEY,7.0,8.0,tt0009369,1918,93,Comedy,Drama,,,Mabel Normand Feature Film Company,,,,,nm0949648,nm0428059,nm0215874,nm0370271,,nm0949648,nm0428059,,nm0635667,nm0629589,nm0479126,nm0168595,,,,,,,nm0784407,nm0413164,,,,,,,,,1.288794e+08,32.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,2.000000e+08,2.450000e+08,DARK PHOENIX,6.1,2458.0,tt6565702,2019,113,Science Fiction,Action,Adventure,,20th Century Fox,Genre Films,Bad Hat Harry Productions,Marvel Entertainment,Kinberg Genre,nm0126208,nm1334526,nm1079211,nm1079208,nm0456158,nm1334526,,,nm0564215,nm1055413,nm2225369,nm0396558,nm0791864,nm1404239,nm5557932,,,,nm2385360,nm3767676,,,,,,,,,4.500000e+07,1.225000
480,6.000000e+06,2.222038e+07,BOOKSMART,7.2,634.0,tt1489887,2019,102,Comedy,,,,Annapurna Pictures,Gary Sanchez Productions,,,,nm1312575,nm4199289,nm2573005,nm2873539,nm1054604,nm1312575,,,nm3239803,nm2788156,nm1790970,nm0837177,nm1094137,nm9537602,,,,,nm2273482,nm1819990,,,,,,,,,1.622038e+07,3.703396
482,9.000000e+06,2.532750e+07,HAPPY DEATH DAY 2U,6.2,1429.0,tt8155288,2019,100,Horror,Mystery,Thriller,Science Fiction,Digital Riot Media,Blumhouse Productions,,,,nm0484907,nm1245146,,,,nm0484907,,,nm1557329,nm3441152,nm7059572,nm4139037,,,,,,,nm0089658,nm0566970,nm0002947,nm3015807,,,,,,,1.632750e+07,2.814167
162,1.750000e+08,5.198028e+08,TOY STORY 4,7.6,3038.0,tt1979376,2019,100,Adventure,Animation,Comedy,Family,Walt Disney Pictures,Pixar,,,,nm2155757,nm1445746,nm0566489,nm0429069,nm0004056,nm2155757,,,nm0000158,nm0000741,nm0001633,nm0355024,,,,,,,,,,,,,,,,,3.448028e+08,2.970302
361,8.000000e+07,1.551526e+08,THE SECRET LIFE OF PETS 2,6.6,822.0,tt5113040,2019,86,Adventure,Animation,Comedy,Family,Universal Pictures,Illumination Entertainment,,,,nm0528244,nm3646390,nm0719208,,,nm3646390,nm0719208,,nm0652663,nm0366389,nm0000148,nm0832314,,,,,,,nm0372329,nm0577560,nm0006035,,,,,,,,7.515255e+07,1.939407

In [ ]:
firstYear = 1914
lastYear = 2019

In [263]:
movies_rev_budget_ratio[movies_rev_budget_ratio['startYear'] == 2018][['vote_average']].mean()[0]

6.507999999999999

In [266]:
mean_rating_by_year[1917] - 2

nan

In [267]:
import numpy as np
import math

mean_rating_by_year = dict.fromkeys(np.arange(firstYear, lastYear + 1), 0)
for i in range(firstYear, lastYear + 1):
    mean_rating_by_year[i] = movies_rev_budget_ratio[movies_rev_budget_ratio['startYear'] == i][['vote_average']].mean()[0]
    if math.isnan(mean_rating_by_year[i]) or mean_rating_by_year[i] == 0:
        mean_rating_by_year[i] = 5.0

In [268]:
mean_rating_by_year

{1914: 5.0,
 1915: 6.0,
 1916: 5.0,
 1917: 5.0,
 1918: 7.0,
 1919: 5.0,
 1920: 5.0,
 1921: 8.3,
 1922: 6.6,
 1923: 5.0,
 1924: 7.5,
 1925: 7.333333333333333,
 1926: 7.35,
 1927: 8.2,
 1928: 6.824999999999999,
 1929: 7.0,
 1930: 6.4,
 1931: 7.475,
 1932: 7.0,
 1933: 5.688888888888889,
 1934: 7.2250000000000005,
 1935: 6.485714285714286,
 1936: 6.699999999999999,
 1937: 4.75,
 1938: 7.6,
 1939: 7.344444444444444,
 1940: 7.3428571428571425,
 1941: 7.228571428571429,
 1942: 6.111111111111112,
 1943: 6.766666666666666,
 1944: 6.9399999999999995,
 1945: 6.2375,
 1946: 7.12,
 1947: 6.2749999999999995,
 1948: 7.128571428571428,
 1949: 6.714285714285714,
 1950: 7.159999999999999,
 1951: 6.81,
 1952: 7.15,
 1953: 6.645454545454545,
 1954: 6.841666666666666,
 1955: 7.45,
 1956: 6.915384615384615,
 1957: 6.925,
 1958: 6.488888888888889,
 1959: 6.6499999999999995,
 1960: 7.339999999999999,
 1961: 6.7250000000000005,
 1962: 7.016666666666666,
 1963: 7.050000000000001,
 1964: 7.142857142857143,
 1965: 7.139999999999999,
 1966: 7.083333333333332,
 1967: 7.184615384615384,
 1968: 6.866666666666666,
 1969: 6.766666666666667,
 1970: 6.721428571428571,
 1971: 7.078571428571428,
 1972: 6.7272727272727275,
 1973: 7.041176470588235,
 1974: 6.946666666666667,
 1975: 6.738461538461537,
 1976: 6.76875,
 1977: 6.588235294117647,
 1978: 6.4375,
 1979: 6.822222222222222,
 1980: 6.55,
 1981: 6.260000000000001,
 1982: 6.274193548387097,
 1983: 6.4125,
 1984: 6.458333333333333,
 1985: 6.6078947368421055,
 1986: 6.272549019607843,
 1987: 6.364814814814814,
 1988: 6.339285714285714,
 1989: 6.417307692307692,
 1990: 6.3535714285714295,
 1991: 6.330303030303029,
 1992: 6.507843137254902,
 1993: 6.231944444444445,
 1994: 6.258064516129031,
 1995: 6.3441558441558445,
 1996: 6.244444444444444,
 1997: 6.203571428571429,
 1998: 6.21125,
 1999: 6.330303030303031,
 2000: 6.126250000000001,
 2001: 6.11219512195122,
 2002: 6.330392156862746,
 2003: 6.13375,
 2004: 6.282474226804124,
 2005: 6.099107142857142,
 2006: 6.087692307692308,
 2007: 6.248648648648649,
 2008: 6.050434782608696,
 2009: 6.091525423728815,
 2010: 6.22781954887218,
 2011: 6.202127659574468,
 2012: 6.2824561403508765,
 2013: 6.258088235294117,
 2014: 6.285123966942149,
 2015: 6.117543859649121,
 2016: 6.327586206896552,
 2017: 6.328155339805826,
 2018: 6.507999999999999,
 2019: 6.738095238095239}

In [284]:
def get_component_score(components, instance, score_type, cur_year):
    score = 0
    cur_year_int = cur_year[['startYear']].iloc[0][0]
    
    weight = len(components)
    for comp in components:
        relevant_cols = cur_year[cur_year[comp] == instance][score_type]
        if score_type == 'vote_average':
            for v in list(relevant_cols.values):
                score += (v - mean_rating_by_year[cur_year_int]) * weight
        else:
            score += sum(list(relevant_cols.values)) * weight
        weight -= 1
    
    return score

In [285]:
movies_rev_budget_ratio

,budget,revenue,title,vote_average,vote_count,tconst,startYear,runtimeMinutes,genre_1,genre_2,genre_3,genre_4,prod_company_1,prod_company_2,prod_company_3,prod_company_4,prod_company_5,writer_1,writer_2,writer_3,writer_4,writer_5,director_1,director_2,director_3,cast_1,cast_2,cast_3,cast_4,cast_5,cast_6,cast_7,cast_8,cast_9,cast_10,others_1,others_2,others_3,others_4,others_5,others_6,others_7,others_8,others_9,others_10,profit,rev_budget_ratio
445,4.265806e+05,2.185334e+06,THE ROSE OF THE RANCHO,0.0,0.0,tt0004545,1914,\N,Romance,Western,Adventure,,Jesse L. Lasky Feature Play Company,,,,,nm0001124,nm0876445,nm0067584,,,nm0001124,,,nm0057585,nm0002034,nm0478890,nm0426668,,,,,,,nm0005931,,,,,,,,,,1.758753e+06,5.122910
3072,2.486208e+06,2.734829e+08,THE BIRTH OF A NATION,6.5,234.0,tt0004972,1915,195,Drama,History,War,,Epoch Film Co.,,,,,nm0228746,nm0000428,nm0940488,,,nm0000428,,,nm0001273,nm0550615,nm0910400,nm0178270,,,,,,,nm0106922,nm0005658,nm0376221,,,,,,,,2.709967e+08,110.000000
353,3.756660e+05,2.541501e+06,THE GIRL OF THE GOLDEN WEST,5.5,2.0,tt0005393,1915,50,Western,Romance,,,Jesse L. Lasky Feature Play Company,,,,,nm0001124,nm0067584,,,,nm0001124,,,nm0885818,nm0731623,nm0676473,nm0454458,,,,,,,nm0005931,nm0371277,,,,,,,,,2.165835e+06,6.765321
103,2.303734e+07,3.202190e+07,A DAUGHTER OF THE GODS,5.0,1.0,tt0006568,1916,180,Fantasy,Drama,,,Fox Film Corporation,,,,,nm0107543,nm5921220,,,,nm0107543,,,nm0445807,nm0790137,nm0208415,nm0393411,,,,,,,nm1135428,nm0005646,nm0191667,nm0402478,,,,,,,8.984562e+06,1.390000
1668,4.157401e+06,1.330368e+08,MICKEY,7.0,8.0,tt0009369,1918,93,Comedy,Drama,,,Mabel Normand Feature Film Company,,,,,nm0949648,nm0428059,nm0215874,nm0370271,,nm0949648,nm0428059,,nm0635667,nm0629589,nm0479126,nm0168595,,,,,,,nm0784407,nm0413164,,,,,,,,,1.288794e+08,32.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,2.000000e+08,2.450000e+08,DARK PHOENIX,6.1,2458.0,tt6565702,2019,113,Science Fiction,Action,Adventure,,20th Century Fox,Genre Films,Bad Hat Harry Productions,Marvel Entertainment,Kinberg Genre,nm0126208,nm1334526,nm1079211,nm1079208,nm0456158,nm1334526,,,nm0564215,nm1055413,nm2225369,nm0396558,nm0791864,nm1404239,nm5557932,,,,nm2385360,nm3767676,,,,,,,,,4.500000e+07,1.225000
480,6.000000e+06,2.222038e+07,BOOKSMART,7.2,634.0,tt1489887,2019,102,Comedy,,,,Annapurna Pictures,Gary Sanchez Productions,,,,nm1312575,nm4199289,nm2573005,nm2873539,nm1054604,nm1312575,,,nm3239803,nm2788156,nm1790970,nm0837177,nm1094137,nm9537602,,,,,nm2273482,nm1819990,,,,,,,,,1.622038e+07,3.703396
482,9.000000e+06,2.532750e+07,HAPPY DEATH DAY 2U,6.2,1429.0,tt8155288,2019,100,Horror,Mystery,Thriller,Science Fiction,Digital Riot Media,Blumhouse Productions,,,,nm0484907,nm1245146,,,,nm0484907,,,nm1557329,nm3441152,nm7059572,nm4139037,,,,,,,nm0089658,nm0566970,nm0002947,nm3015807,,,,,,,1.632750e+07,2.814167
162,1.750000e+08,5.198028e+08,TOY STORY 4,7.6,3038.0,tt1979376,2019,100,Adventure,Animation,Comedy,Family,Walt Disney Pictures,Pixar,,,,nm2155757,nm1445746,nm0566489,nm0429069,nm0004056,nm2155757,,,nm0000158,nm0000741,nm0001633,nm0355024,,,,,,,,,,,,,,,,,3.448028e+08,2.970302
361,8.000000e+07,1.551526e+08,THE SECRET LIFE OF PETS 2,6.6,822.0,tt5113040,2019,86,Adventure,Animation,Comedy,Family,Universal Pictures,Illumination Entertainment,,,,nm0528244,nm3646390,nm0719208,,,nm3646390,nm0719208,,nm0652663,nm0366389,nm0000148,nm0832314,,,,,,,nm0372329,nm0577560,nm0006035,,,,,,,,7.515255e+07,1.939407

In [286]:
movies_rev_budget_ratio[(movies_rev_budget_ratio['writer_1'] == 'nm0634240') | 
                        (movies_rev_budget_ratio['writer_2'] == 'nm0634240') |
                        (movies_rev_budget_ratio['writer_3'] == 'nm0634240') |
                        (movies_rev_budget_ratio['writer_4'] == 'nm0634240') |
                        (movies_rev_budget_ratio['writer_5'] == 'nm0634240')]

,budget,revenue,title,vote_average,vote_count,tconst,startYear,runtimeMinutes,genre_1,genre_2,genre_3,genre_4,prod_company_1,prod_company_2,prod_company_3,prod_company_4,prod_company_5,writer_1,writer_2,writer_3,writer_4,writer_5,director_1,director_2,director_3,cast_1,cast_2,cast_3,cast_4,cast_5,cast_6,cast_7,cast_8,cast_9,cast_10,others_1,others_2,others_3,others_4,others_5,others_6,others_7,others_8,others_9,others_10,profit,rev_budget_ratio
2890,1.312406e+07,5.792536e+07,MEMENTO,8.2,8368.0,tt0209144,2000,113,Mystery,Thriller,,,Summit Entertainment,Newmarket Capital Group,Team Todd,I Remember Productions,,nm0634240,nm0634300,,,,nm0634240,,,nm0001602,nm0005251,nm0001592,nm0095478,nm0719678,,,,,,nm0865189,nm0865297,nm0432382,nm0002892,,,,,,,4.480130e+07,4.413677
2978,6.420746e+07,1.587248e+08,INSOMNIA,6.9,2409.0,tt0278504,2002,118,Crime,Mystery,Thriller,,Alcon Entertainment,Witt/Thomas Productions,Section Eight,,,nm0296154,nm0782711,nm0634240,nm0804408,,nm0634240,,,nm0000199,nm0000245,nm0005476,nm0233027,,,,,,,nm0424663,nm0432625,nm0233827,nm0859597,,,,,,,9.451733e+07,2.472062
3210,4.982282e+07,1.366096e+08,THE PRESTIGE,8.2,8791.0,tt0482571,2006,130,Drama,Mystery,Thriller,,Touchstone Pictures,Syncopy,Warner Bros. Pictures,,,nm1793993,nm0634240,nm0634300,,,nm0634240,,,nm0000288,nm0413168,nm0424060,nm0000323,nm0356017,,,,,,nm0753083,nm0858799,nm0432382,nm0002892,nm0250373,,,,,,8.678675e+07,2.741908
2047,2.734250e+08,1.186598e+09,THE DARK KNIGHT RISES,7.7,14735.0,tt1345836,2012,164,Action,Crime,Drama,Thriller,Syncopy,Legendary Entertainment,DC Entertainment,Warner Bros. Pictures,,nm0333060,nm0004170,nm0634240,nm0634300,,nm0634240,,,nm0000288,nm0362766,nm0004266,nm0000198,nm0000546,nm1577637,,,,,nm0746273,nm0858799,nm0004012,,,,,,,,9.131730e+08,4.339756

In [287]:
success_metrics = ['vote_average', 'vote_count', 'profit', 'rev_budget_ratio']
nontrivial_col_types = [prod_companies_cols, writers_cols, directors_cols, cast_cols, others_cols]

In [288]:
get_component_score(writers_cols, 'nm0634240', success_metrics[0], movies[movies['startYear'] == 2000])

10.368749999999993

In [92]:
get_component_score(writers_cols, 'nm0634240', success_metrics[1], movies[movies['startYear'] == 2002])

7227.0

In [93]:
get_component_score(writers_cols, 'nm0634240', success_metrics[2], movies[movies['startYear'] == 2012])

2739519138.121114

In [94]:
get_component_score(writers_cols, 'nm0634240', success_metrics[3], movies[movies['startYear'] == 2006])

10.9676311

In [451]:
!pip3 install dill --user

Processing /home/trb116/.cache/pip/wheels/59/b1/91/f02e76c732915c4015ab4010f3015469866c1eb9b14058d8e7/dill-0.3.1.1-cp37-none-any.whl
Installing collected packages: dill
Successfully installed dill-0.3.1.1

In [452]:
import dill
dill.dump_session('notebook_env.db')

In [453]:
movies_rev_budget_ratio.to_csv('movies_rev_budget_ratio.csv')

In [1]:
import dill
dill.load_session('notebook_env.db')

/home/trb116/.local/lib/python3.7/site-packages/cpi/__init__.py:46: StaleDataWarning: CPI data is out of date. To accurately inflate to today's dollars, you must run `cpi.update()`.
  warnings.warn(StaleDataWarning())

In [49]:
movies = movies_rev_budget_ratio.copy()

In [10]:
movies

,budget,revenue,title,vote_average,vote_count,tconst,startYear,runtimeMinutes,genre_1,genre_2,...,others_3,others_4,others_5,others_6,others_7,others_8,others_9,others_10,profit,rev_budget_ratio
445,4.265806e+05,2.185334e+06,THE ROSE OF THE RANCHO,0.0,0.0,tt0004545,1914,\N,Romance,Western,...,,,,,,,,,1.758753e+06,5.122910
3072,2.486208e+06,2.734829e+08,THE BIRTH OF A NATION,6.5,234.0,tt0004972,1915,195,Drama,History,...,nm0376221,,,,,,,,2.709967e+08,110.000000
353,3.756660e+05,2.541501e+06,THE GIRL OF THE GOLDEN WEST,5.5,2.0,tt0005393,1915,50,Western,Romance,...,,,,,,,,,2.165835e+06,6.765321
103,2.303734e+07,3.202190e+07,A DAUGHTER OF THE GODS,5.0,1.0,tt0006568,1916,180,Fantasy,Drama,...,nm0191667,nm0402478,,,,,,,8.984562e+06,1.390000
1668,4.157401e+06,1.330368e+08,MICKEY,7.0,8.0,tt0009369,1918,93,Comedy,Drama,...,,,,,,,,,1.288794e+08,32.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,2.000000e+08,2.450000e+08,DARK PHOENIX,6.1,2458.0,tt6565702,2019,113,Science Fiction,Action,...,,,,,,,,,4.500000e+07,1.225000
480,6.000000e+06,2.222038e+07,BOOKSMART,7.2,634.0,tt1489887,2019,102,Comedy,,...,,,,,,,,,1.622038e+07,3.703396
482,9.000000e+06,2.532750e+07,HAPPY DEATH DAY 2U,6.2,1429.0,tt8155288,2019,100,Horror,Mystery,...,nm0002947,nm3015807,,,,,,,1.632750e+07,2.814167
162,1.750000e+08,5.198028e+08,TOY STORY 4,7.6,3038.0,tt1979376,2019,100,Adventure,Animation,...,,,,,,,,,3.448028e+08,2.970302
361,8.000000e+07,1.551526e+08,THE SECRET LIFE OF PETS 2,6.6,822.0,tt5113040,2019,86,Adventure,Animation,...,nm0006035,,,,,,,,7.515255e+07,1.939407

In [54]:
success_metrics

['vote_average', 'vote_count', 'profit', 'rev_budget_ratio']

In [148]:
nontrivial_col_types

[['prod_company_1',
  'prod_company_2',
  'prod_company_3',
  'prod_company_4',
  'prod_company_5'],
 ['writer_1', 'writer_2', 'writer_3', 'writer_4', 'writer_5'],
 ['director_1', 'director_2', 'director_3'],
 ['cast_1',
  'cast_2',
  'cast_3',
  'cast_4',
  'cast_5',
  'cast_6',
  'cast_7',
  'cast_8',
  'cast_9',
  'cast_10'],
 ['others_1',
  'others_2',
  'others_3',
  'others_4',
  'others_5',
  'others_6',
  'others_7',
  'others_8',
  'others_9',
  'others_10']]

In [259]:
%%time
import numpy
import statistics

total_scores_keys = []
for col_type in nontrivial_col_types:
    for metric in success_metrics:
        total_scores_keys.append(col_type[0][:-2] + '|' + metric)
total_scores = dict.fromkeys(total_scores_keys, 0)

individual_scores = {}

movies_encoded = movies.copy()
for metric in success_metrics:
    for col_type in nontrivial_col_types:
        for col in col_type:
            movies_encoded[col + '_' + metric] = 0.0
        
for i in range(firstYear, lastYear):
    print(i)
    cur_year = movies_encoded[movies_encoded['startYear'] == i]

    for col_type in nontrivial_col_types:
        for metric in success_metrics:            
            all_ids = set()
            rows = cur_year[col_type].values
            for row in rows:
                for id_ in row:
                    if id_ != '' and id_ not in all_ids:
                        all_ids.add(id_)

            for id_ in all_ids:
                key_code = col_type[0][:-2] + '|' + metric + '|' + id_
                if key_code not in individual_scores:
                    individual_scores.update({key_code: 0})
                score = get_component_score(col_type, id_, metric, cur_year)
                individual_scores[key_code] +=  score
                total_scores[col_type[0][:-2] + '|' + metric] += score
                
    normalized_scores = individual_scores.copy()            
    
    for col_type in nontrivial_col_types:
        for metric in success_metrics:
            all_values = []
            
            for key in individual_scores.keys():
                if key.find(col_type[0][:-2] + '|' + metric) != -1:
                    all_values.append(individual_scores[key])
                    
            if len(all_values) < 2:
#                 print(i)
                for key in normalized_scores.keys():
                    normalized_scores[key] = 0
                continue
                    
            std = statistics.stdev(all_values)
            mean = statistics.mean(all_values)
            
                
            for key in normalized_scores.keys():
                if key.find(col_type[0][:-2] + '|' + metric) != -1:
                    normalized = individual_scores[key]
                    normalized -= mean
                    normalized /= std
                    if(std != 0):
                        normalized_scores[key] = normalized
                    else:
                        normalized_scores[key] = 0
    for index, row in cur_year.iterrows():
        for col_type in nontrivial_col_types:
            for metric in success_metrics:
                for col in col_type:
                    id_ = row[col]
                    if id_ != '':            
                        key_code = col_type[0][:-2] + '|' + metric + '|' + id_
                        movies_encoded.set_value(index, col + '_' + metric, normalized_scores[key_code])

1914

/home/trb116/.local/lib/python3.7/site-packages/ipykernel_launcher.py:64: RuntimeWarning: invalid value encountered in double_scalars
/home/trb116/.local/lib/python3.7/site-packages/ipykernel_launcher.py:76: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
CPU times: user 22min 44s, sys: 2.09 s, total: 22min 46s
Wall time: 22min 42s

In [253]:
normalized_scores

{'prod_company|vote_average|Jesse L. Lasky Feature Play Company': -0.21821789023599208,
 'prod_company|vote_count|Jesse L. Lasky Feature Play Company': -0.573621449419899,
 'prod_company|profit|Jesse L. Lasky Feature Play Company': -0.5938335246634768,
 'prod_company|rev_budget_ratio|Jesse L. Lasky Feature Play Company': -0.4875068663161153,
 'writer|vote_average|nm0001124': 0.6123045940697407,
 'writer|vote_average|nm0067584': 0.0451171806156651,
 'writer|vote_average|nm0876445': -2.223632473200637,
 'writer|vote_count|nm0001124': -0.6920496748081366,
 'writer|vote_count|nm0067584': -0.6960688380738099,
 'writer|vote_count|nm0876445': -0.7121454911365035,
 'writer|profit|nm0001124': -0.7086214463082946,
 'writer|profit|nm0067584': -0.7186383451427746,
 'writer|profit|nm0876445': -0.7308076905082727,
 'writer|rev_budget_ratio|nm0001124': -0.5504256974113731,
 'writer|rev_budget_ratio|nm0067584': -0.6269126000596974,
 'writer|rev_budget_ratio|nm0876445': -0.725553731354735,
 'director|vote_average|nm0001124': -0.2182178902359924,
 'director|vote_count|nm0001124': -0.573621449419899,
 'director|profit|nm0001124': -0.5938335246634768,
 'director|rev_budget_ratio|nm0001124': -0.4875068663161154,
 'cast|vote_average|nm0426668': -1.585736965338499,
 'cast|vote_average|nm0478890': -1.585736965338499,
 'cast|vote_average|nm0002034': -1.585736965338499,
 'cast|vote_average|nm0057585': -1.585736965338499,
 'cast|vote_count|nm0426668': -0.562098189739413,
 'cast|vote_count|nm0478890': -0.562098189739413,
 'cast|vote_count|nm0002034': -0.562098189739413,
 'cast|vote_count|nm0057585': -0.562098189739413,
 'cast|profit|nm0426668': -0.5759489496388234,
 'cast|profit|nm0478890': -0.5742349534276423,
 'cast|profit|nm0002034': -0.5725209572164613,
 'cast|profit|nm0057585': -0.5708069610052804,
 'cast|rev_budget_ratio|nm0426668': -0.5559473438087587,
 'cast|rev_budget_ratio|nm0478890': -0.5433511720446444,
 'cast|rev_budget_ratio|nm0002034': -0.5307550002805304,
 'cast|rev_budget_ratio|nm0057585': -0.5181588285164163,
 'others|vote_average|nm0005931': 0.5437272478270369,
 'others|vote_count|nm0005931': -0.6549434303930914,
 'others|profit|nm0005931': -0.6802028909762876,
 'others|rev_budget_ratio|nm0005931': -0.49184288046802016,
 'prod_company|vote_average|Epoch Film Co.': 1.0910894511799623,
 'prod_company|vote_count|Epoch Film Co.': 1.1546925280530433,
 'prod_company|profit|Epoch Film Co.': 1.154542151845898,
 'prod_company|rev_budget_ratio|Epoch Film Co.': 1.1502592475194333,
 'writer|vote_average|nm0000428': 0.4576171176731746,
 'writer|vote_average|nm0940488': -0.21269528004527832,
 'writer|vote_average|nm0228746': 1.1279295153916276,
 'writer|vote_count|nm0000428': 1.1688229171986424,
 'writer|vote_count|nm0940488': 0.6985808151148558,
 'writer|vote_count|nm0228746': 1.6390650192824288,
 'writer|profit|nm0000428': 1.1673211884604981,
 'writer|profit|nm0940488': 0.6896891631658141,
 'writer|profit|nm0228746': 1.6449532137551819,
 'writer|rev_budget_ratio|nm0000428': 1.1606744733850027,
 'writer|rev_budget_ratio|nm0940488': 0.6660833689447061,
 'writer|rev_budget_ratio|nm0228746': 1.6552655778252994,
 'director|vote_average|nm0000428': 1.091089451179962,
 'director|vote_count|nm0000428': 1.1546925280530436,
 'director|profit|nm0000428': 1.1545421518458978,
 'director|rev_budget_ratio|nm0000428': 1.1502592475194335,
 'cast|vote_average|nm0178270': 0.41152343391137514,
 'cast|vote_average|nm0885818': 0.8285338469415686,
 'cast|vote_average|nm0676473': 0.34567968448555514,
 'cast|vote_average|nm0731623': 0.5871067657135619,
 'cast|vote_average|nm0910400': 0.6968463480899286,
 'cast|vote_average|nm0550615': 0.982169262268482,
 'cast|vote_average|nm0454458': 0.10425260325754837,
 'cast|vote_average|nm0001273': 1.2674921764470355,
 'cast|vote_count|nm0178270': 1.2660811794204945,
 'cast|vote_count|nm0885818': -0.5397760973198781,
 'cast|vote_count|nm0676473': -0.5442405158037851,
 'cast|vote_count|nm0731623': -0.5420083065618315,
 'cast|vote_count|nm0910400': 1.5272496607290527,
 'cast|vote_count|nm0550615': 1.7884181420376108,
 'cast|vote_count|nm0454458': -0.5464727250457385,
 'cast|vote_count|nm0001273': 2.049586623346169,
 'cast|profit|nm0178270': 1.2607549631192108,
 'cast|profit|nm0885818': -0.5668397388290708,
 'cast|profit|nm0676473': -0.5710611756866747,
 'cast|profit|nm0731623': -0.5689504572578729,
 'cast|profit|nm0910400': 1.5248552325815397,
 'cast|profit|nm0550615': 1.7889555020438686,
 'cast|profit|nm0454458': -0.5731718941154766,
 'cast|profit|nm0001273': 2.0530557715061972,
 'cast|rev_budget_ratio|nm0178270': 1.2491494332186603,
 'cast|rev_budget_ratio|nm0885818': -0.47777536289391126,
 'cast|rev_budget_ratio|nm0676473': -0.5110443995466405,
 'cast|rev_budget_ratio|nm0731623': -0.4944098812202759,
 'cast|rev_budget_ratio|nm0910400': 1.5196165731295488,
 'cast|rev_budget_ratio|nm0550615': 1.790083713040437,
 'cast|rev_budget_ratio|nm0454458': -0.5276789178730051,
 'cast|rev_budget_ratio|nm0001273': 2.0605508529513252,
 'others|vote_average|nm0005658': 0.9243363213059627,
 'others|vote_average|nm0371277': -0.054372724782703684,
 'others|vote_average|nm0106922': 1.6311817434811104,
 'others|vote_average|nm0376221': 0.21749089913081474,
 'others|vote_count|nm0005658': 1.3250739548242836,
 'others|vote_count|nm0371277': -0.6568418171478541,
 'others|vote_count|nm0106922': 1.547185205131506,
 'others|vote_count|nm0376221': 1.1029627045170614,
 'others|profit|nm0005658': 1.3245559575319341,
 'others|profit|nm0371277': -0.6967050973955428,
 'others|profit|nm0106922': 1.5509498843779983,
 'others|profit|nm0376221': 1.0981620306858697,
 'others|rev_budget_ratio|nm0005658': 1.3209992671259205,
 'others|rev_budget_ratio|nm0371277': -0.6125323549889363,
 'others|rev_budget_ratio|nm0106922': 1.5499151060998095,
 'others|rev_budget_ratio|nm0376221': 1.092083428152032,
 'prod_company|vote_average|Fox Film Corporation': -0.8728715609439692,
 'prod_company|vote_count|Fox Film Corporation': -0.5810710786331444,
 'prod_company|profit|Fox Film Corporation': -0.5607086271824212,
 'prod_company|rev_budget_ratio|Fox Film Corporation': -0.6627523812033179,
 'writer|vote_average|nm5921220': -0.16113278791308966,
 'writer|vote_average|nm0107543': 0.3544921334087972,
 'writer|vote_count|nm5921220': -0.7041071646051568,
 'writer|vote_count|nm0107543': -0.7020975829723201,
 'writer|profit|nm5921220': -0.6798656940452052,
 'writer|profit|nm0107543': -0.664030389376947,
 'writer|rev_budget_ratio|nm5921220': -0.7926906121881104,
 'writer|rev_budget_ratio|nm0107543': -0.7864407791410922,
 'director|vote_average|nm0107543': -0.8728715609439696,
 'director|vote_count|nm0107543': -0.5810710786331444,
 'director|profit|nm0107543': -0.5607086271824212,
 'director|rev_budget_ratio|nm0107543': -0.662752381203318,
 'cast|vote_average|nm0393411': -0.04938281206936502,
 'cast|vote_average|nm0445807': 0.6090546821888352,
 'cast|vote_average|nm0790137': 0.3895755174361018,
 'cast|vote_average|nm0208415': 0.1700963526833684,
 'cast|vote_count|nm0393411': -0.5542854573925757,
 'cast|vote_count|nm0445807': -0.5509371435296455,
 'cast|vote_count|nm0790137': -0.5520532481506223,
 'cast|vote_count|nm0208415': -0.553169352771599,
 'cast|profit|nm0393411': -0.5266554768593276,
 'cast|profit|nm0445807': -0.5003877141774293,
 'cast|profit|nm0790137': -0.5091436350713955,
 'cast|profit|nm0208415': -0.5178995559653615,
 'cast|rev_budget_ratio|nm0393411': -0.6201964982363489,
 'cast|rev_budget_ratio|nm0445807': -0.6099433348415453,
 'cast|rev_budget_ratio|nm0790137': -0.6133610559731465,
 'cast|rev_budget_ratio|nm0208415': -0.6167787771047477,
 'others|vote_average|nm0402478': -1.6311817434811104,
 'others|vote_average|nm0005646': -0.5437272478270369,
 'others|vote_average|nm0191667': -1.0874544956540737,
 'others|vote_average|nm1135428': 0.0,
 'others|vote_count|nm0402478': -0.6672829442990483,
 'others|vote_count|nm0005646': -0.6653845575442857,
 'others|vote_count|nm0191667': -0.666333750921667,
 'others|vote_count|nm1135428': -0.6644353641669044,
 'others|profit|nm0402478': -0.6604486910018728,
 'others|profit|nm0005646': -0.6454370644073665,
 'others|profit|nm0191667': -0.6529428777046196,
 'others|profit|nm1135428': -0.6379312511101133,
 'others|rev_budget_ratio|nm0402478': -0.7189946371552972,
 'others|rev_budget_ratio|nm0005646': -0.7132093095885026,
 'others|rev_budget_ratio|nm0191667': -0.7161019733719,
 'others|rev_budget_ratio|nm1135428': -0.7103166458051053}

In [252]:
movies_encoded[movies_encoded['startYear'] < 1917]

,budget,revenue,title,vote_average,vote_count,tconst,startYear,runtimeMinutes,genre_1,genre_2,genre_3,genre_4,prod_company_1,prod_company_2,prod_company_3,prod_company_4,prod_company_5,writer_1,writer_2,writer_3,writer_4,writer_5,director_1,director_2,director_3,cast_1,cast_2,cast_3,cast_4,cast_5,cast_6,cast_7,cast_8,cast_9,cast_10,others_1,others_2,others_3,others_4,others_5,others_6,others_7,others_8,others_9,others_10,profit,rev_budget_ratio,prod_company_1_vote_average,prod_company_2_vote_average,prod_company_3_vote_average,prod_company_4_vote_average,prod_company_5_vote_average,writer_1_vote_average,writer_2_vote_average,writer_3_vote_average,writer_4_vote_average,writer_5_vote_average,director_1_vote_average,director_2_vote_average,director_3_vote_average,cast_1_vote_average,cast_2_vote_average,cast_3_vote_average,cast_4_vote_average,cast_5_vote_average,cast_6_vote_average,cast_7_vote_average,cast_8_vote_average,cast_9_vote_average,cast_10_vote_average,others_1_vote_average,others_2_vote_average,others_3_vote_average,others_4_vote_average,others_5_vote_average,others_6_vote_average,others_7_vote_average,others_8_vote_average,others_9_vote_average,others_10_vote_average,prod_company_1_vote_count,prod_company_2_vote_count,prod_company_3_vote_count,prod_company_4_vote_count,prod_company_5_vote_count,writer_1_vote_count,writer_2_vote_count,writer_3_vote_count,writer_4_vote_count,writer_5_vote_count,director_1_vote_count,director_2_vote_count,director_3_vote_count,cast_1_vote_count,cast_2_vote_count,cast_3_vote_count,cast_4_vote_count,cast_5_vote_count,cast_6_vote_count,cast_7_vote_count,cast_8_vote_count,cast_9_vote_count,cast_10_vote_count,others_1_vote_count,others_2_vote_count,others_3_vote_count,others_4_vote_count,others_5_vote_count,others_6_vote_count,others_7_vote_count,others_8_vote_count,others_9_vote_count,others_10_vote_count,prod_company_1_profit,prod_company_2_profit,prod_company_3_profit,prod_company_4_profit,prod_company_5_profit,writer_1_profit,writer_2_profit,writer_3_profit,writer_4_profit,writer_5_profit,director_1_profit,director_2_profit,director_3_profit,cast_1_profit,cast_2_profit,cast_3_profit,cast_4_profit,cast_5_profit,cast_6_profit,cast_7_profit,cast_8_profit,cast_9_profit,cast_10_profit,others_1_profit,others_2_profit,others_3_profit,others_4_profit,others_5_profit,others_6_profit,others_7_profit,others_8_profit,others_9_profit,others_10_profit,prod_company_1_rev_budget_ratio,prod_company_2_rev_budget_ratio,prod_company_3_rev_budget_ratio,prod_company_4_rev_budget_ratio,prod_company_5_rev_budget_ratio,writer_1_rev_budget_ratio,writer_2_rev_budget_ratio,writer_3_rev_budget_ratio,writer_4_rev_budget_ratio,writer_5_rev_budget_ratio,director_1_rev_budget_ratio,director_2_rev_budget_ratio,director_3_rev_budget_ratio,cast_1_rev_budget_ratio,cast_2_rev_budget_ratio,cast_3_rev_budget_ratio,cast_4_rev_budget_ratio,cast_5_rev_budget_ratio,cast_6_rev_budget_ratio,cast_7_rev_budget_ratio,cast_8_rev_budget_ratio,cast_9_rev_budget_ratio,cast_10_rev_budget_ratio,others_1_rev_budget_ratio,others_2_rev_budget_ratio,others_3_rev_budget_ratio,others_4_rev_budget_ratio,others_5_rev_budget_ratio,others_6_rev_budget_ratio,others_7_rev_budget_ratio,others_8_rev_budget_ratio,others_9_rev_budget_ratio,others_10_rev_budget_ratio
445,4.265806e+05,2.185334e+06,THE ROSE OF THE RANCHO,0.0,0.0,tt0004545,1914,\N,Romance,Western,Adventure,,Jesse L. Lasky Feature Play Company,,,,,nm0001124,nm0876445,nm0067584,,,nm0001124,,,nm0057585,nm0002034,nm0478890,nm0426668,,,,,,,nm0005931,,,,,,,,,,1.758753e+06,5.122910,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3072,2.486208e+06,2.734829e+08,THE BIRTH OF A NATION,6.5,234.0,tt0004972,1915,195,Drama,History,War,,Epoch Film Co.,,,,,nm0228746,nm0000428,nm0940488,,,nm0000428,,,nm0001273,nm0550615,nm0910400,nm0178270,,,,,,,nm0106922,nm0005658,nm0376221,,,,,,,,2.709967e+08,110.000000,0.707107,0.0,0.0,0.0,0.0,0.991757,0.418742,-0.154273,0.0,0.0,0.707107,0.0,0.0,1.191747,0.941864,0.691982,0.442100,0.0,0.0,0.0,0.0,0.0,0.0,1.487146,0.413096,-0.660954,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.707107,0.0,0.0,0.0,0.0,1.317734,0.876604,0.435474,0.0,0.0,0.707107,0.0,0.0,1.691911,1.455030,1.218149,0.981268,0.0,0.0,0.0,0.0,0.0,0.0,0.925360,0.722764,0.520168,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.707107,0.0,0.0,0.0,0.0,1.319812,0.876182,0.432553,0.0,0.0,0.707107,0.0,0.0,1.692887,1.455310,1.217733,0.980156,0.0,0.0,0.0,0.0,0.0,0.0,0.925908,0.722709,0.519510,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.707107,0.0,0.0,0.0,0.0,1.347341,0.868644,0.389947,0.0,0.0,0.707107,0.0,0.0,1.708001,1.459038,1.210075,0.961111,0.0,0.0,0.0,0.0,0.0,0.0,0.940972,0.720766,0.500560,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
353,3.756660e+05,2.541501e+06,THE GIRL OF THE GOLDEN WEST,5.5,2.0,tt0005393,1915,50,Western,Romance,,,Jesse L. Lasky Feature Play Company,,,,,nm0001124,nm0067584,,,,nm0001124,,,nm0885818,nm0731623,nm0676473,nm0454458,,,,,,,nm0005931,nm0371277,,,,,,,,,2.165835e+06,6.765321,-0.707107,0.0,0.0,0.0,0.0,0.550976,0.066117,0.000000,0.0,0.0,-0.707107,0.0,0.0,0.807312,0.595873,0.384434,0.172996,0.0,0.0,0.0,0.0,0.0,0.0,-0.165238,-1.074050,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,-0.707107,0.0,0.0,0.0,0.0,-0.869064,-0.872834,0.000000,0.0,0.0,-0.707107,0.0,0.0,-0.656653,-0.658678,-0.660702,-0.662727,0.0,0.0,0.0,0.0,0.0,0.0,-1.083280,-1.085012,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,-0.707107,0.0,0.0,0.0,0.0,-0.866212,-0.875516,0.000000,0.0,0.0,-0.707107,0.0,0.0,-0.663896,-0.665795,-0.667693,-0.669592,0.0,0.0,0.0,0.0,0.0,0.0,-1.076657,-1.091469,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,-0.707107,0.0,0.0,0.0,0.0,-0.787468,-0.861497,0.000000,0.0,0.0,-0.707107,0.0,0.0,-0.628512,-0.643824,-0.659136,-0.674448,0.0,0.0,0.0,0.0,0.0,0.0,-1.023101,-1.139198,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
103,2.303734e+07,3.202190e+07,A DAUGHTER OF THE GODS,5.0,1.0,tt0006568,1916,180,Fantasy,Drama,,,Fox Film Corporation,,,,,nm0107543,nm5921220,,,,nm0107543,,,nm0445807,nm0790137,nm0208415,nm0393411,,,,,,,nm1135428,nm0005646,nm0191667,nm0402478,,,,,,,8.984562e+06,1.390000,-0.872872,0.0,0.0,0.0,0.0,0.354492,-0.161133,0.000000,0.0,0.0,-0.872872,0.0,0.0,0.609055,0.389576,0.170096,-0.049383,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,-0.543727,-1.087454,-1.631182,0.0,0.0,0.0,0.0,0.0,0.0,-0.581071,0.0,0.0,0.0,0.0,-0.702098,-0.704107,0.000000,0.0,0.0,-0.581071,0.0,0.0,-0.550937,-0.552053,-0.553169,-0.554285,0.0,0.0,0.0,0.0,0.0,0.0,-0.664435,-0.665385,-0.666334,-0.667283,0.0,0.0,0.0,0.0,0.0,0.0,-0.560709,0.0,0.0,0.0,0.0,-0.664030,-0.679866,0.000000,0.0,0.0,-0.560709,0.0,0.0,-0.500388,-0.509144,-0.517900,-0.526655,0.0,0.0,0.0,0.0,0.0,0.0,-0.637931,-0.645437,-0.652943,-0.660449,0.0,0.0,0.0,0.0,0.0,0.0,-0.662752,0.0,0.0,0.0,0.0,-0.786441,-0.792691,0.000000,0.0,0.0,-0.662752,0.0,0.0,-0.609943,-0.613361,-0.616779,-0.620196,0.0,0.0,0.0,0.0,0.0,0.0,-0.710317,-0.713209,-0.716102,-0.718995,0.0,0.0,0.0,0.0,0.0,0.0

In [235]:
normalized_scores

{'prod_company|vote_average|Jesse L. Lasky Feature Play Company': -0.21821789023599208,
 'prod_company|vote_count|Jesse L. Lasky Feature Play Company': -0.573621449419899,
 'prod_company|profit|Jesse L. Lasky Feature Play Company': -0.5938335246634768,
 'prod_company|rev_budget_ratio|Jesse L. Lasky Feature Play Company': -0.4875068663161153,
 'writer|vote_average|nm0001124': 0.6123045940697407,
 'writer|vote_average|nm0067584': 0.0451171806156651,
 'writer|vote_average|nm0876445': -2.223632473200637,
 'writer|vote_count|nm0001124': -0.6920496748081366,
 'writer|vote_count|nm0067584': -0.6960688380738099,
 'writer|vote_count|nm0876445': -0.7121454911365035,
 'writer|profit|nm0001124': -0.7086214463082946,
 'writer|profit|nm0067584': -0.7186383451427746,
 'writer|profit|nm0876445': -0.7308076905082727,
 'writer|rev_budget_ratio|nm0001124': -0.5504256974113731,
 'writer|rev_budget_ratio|nm0067584': -0.6269126000596974,
 'writer|rev_budget_ratio|nm0876445': -0.725553731354735,
 'director|vote_average|nm0001124': -0.2182178902359924,
 'director|vote_count|nm0001124': -0.573621449419899,
 'director|profit|nm0001124': -0.5938335246634768,
 'director|rev_budget_ratio|nm0001124': -0.4875068663161154,
 'cast|vote_average|nm0426668': -1.585736965338499,
 'cast|vote_average|nm0478890': -1.585736965338499,
 'cast|vote_average|nm0002034': -1.585736965338499,
 'cast|vote_average|nm0057585': -1.585736965338499,
 'cast|vote_count|nm0426668': -0.562098189739413,
 'cast|vote_count|nm0478890': -0.562098189739413,
 'cast|vote_count|nm0002034': -0.562098189739413,
 'cast|vote_count|nm0057585': -0.562098189739413,
 'cast|profit|nm0426668': -0.5759489496388234,
 'cast|profit|nm0478890': -0.5742349534276423,
 'cast|profit|nm0002034': -0.5725209572164613,
 'cast|profit|nm0057585': -0.5708069610052804,
 'cast|rev_budget_ratio|nm0426668': -0.5559473438087587,
 'cast|rev_budget_ratio|nm0478890': -0.5433511720446444,
 'cast|rev_budget_ratio|nm0002034': -0.5307550002805304,
 'cast|rev_budget_ratio|nm0057585': -0.5181588285164163,
 'others|vote_average|nm0005931': 0.5437272478270369,
 'others|vote_count|nm0005931': -0.6549434303930914,
 'others|profit|nm0005931': -0.6802028909762876,
 'others|rev_budget_ratio|nm0005931': -0.49184288046802016,
 'prod_company|vote_average|Epoch Film Co.': 1.0910894511799623,
 'prod_company|vote_count|Epoch Film Co.': 1.1546925280530433,
 'prod_company|profit|Epoch Film Co.': 1.154542151845898,
 'prod_company|rev_budget_ratio|Epoch Film Co.': 1.1502592475194333,
 'writer|vote_average|nm0000428': 0.4576171176731746,
 'writer|vote_average|nm0940488': -0.21269528004527832,
 'writer|vote_average|nm0228746': 1.1279295153916276,
 'writer|vote_count|nm0000428': 1.1688229171986424,
 'writer|vote_count|nm0940488': 0.6985808151148558,
 'writer|vote_count|nm0228746': 1.6390650192824288,
 'writer|profit|nm0000428': 1.1673211884604981,
 'writer|profit|nm0940488': 0.6896891631658141,
 'writer|profit|nm0228746': 1.6449532137551819,
 'writer|rev_budget_ratio|nm0000428': 1.1606744733850027,
 'writer|rev_budget_ratio|nm0940488': 0.6660833689447061,
 'writer|rev_budget_ratio|nm0228746': 1.6552655778252994,
 'director|vote_average|nm0000428': 1.091089451179962,
 'director|vote_count|nm0000428': 1.1546925280530436,
 'director|profit|nm0000428': 1.1545421518458978,
 'director|rev_budget_ratio|nm0000428': 1.1502592475194335,
 'cast|vote_average|nm0178270': 0.41152343391137514,
 'cast|vote_average|nm0885818': 0.8285338469415686,
 'cast|vote_average|nm0676473': 0.34567968448555514,
 'cast|vote_average|nm0731623': 0.5871067657135619,
 'cast|vote_average|nm0910400': 0.6968463480899286,
 'cast|vote_average|nm0550615': 0.982169262268482,
 'cast|vote_average|nm0454458': 0.10425260325754837,
 'cast|vote_average|nm0001273': 1.2674921764470355,
 'cast|vote_count|nm0178270': 1.2660811794204945,
 'cast|vote_count|nm0885818': -0.5397760973198781,
 'cast|vote_count|nm0676473': -0.5442405158037851,
 'cast|vote_count|nm0731623': -0.5420083065618315,
 'cast|vote_count|nm0910400': 1.5272496607290527,
 'cast|vote_count|nm0550615': 1.7884181420376108,
 'cast|vote_count|nm0454458': -0.5464727250457385,
 'cast|vote_count|nm0001273': 2.049586623346169,
 'cast|profit|nm0178270': 1.2607549631192108,
 'cast|profit|nm0885818': -0.5668397388290708,
 'cast|profit|nm0676473': -0.5710611756866747,
 'cast|profit|nm0731623': -0.5689504572578729,
 'cast|profit|nm0910400': 1.5248552325815397,
 'cast|profit|nm0550615': 1.7889555020438686,
 'cast|profit|nm0454458': -0.5731718941154766,
 'cast|profit|nm0001273': 2.0530557715061972,
 'cast|rev_budget_ratio|nm0178270': 1.2491494332186603,
 'cast|rev_budget_ratio|nm0885818': -0.47777536289391126,
 'cast|rev_budget_ratio|nm0676473': -0.5110443995466405,
 'cast|rev_budget_ratio|nm0731623': -0.4944098812202759,
 'cast|rev_budget_ratio|nm0910400': 1.5196165731295488,
 'cast|rev_budget_ratio|nm0550615': 1.790083713040437,
 'cast|rev_budget_ratio|nm0454458': -0.5276789178730051,
 'cast|rev_budget_ratio|nm0001273': 2.0605508529513252,
 'others|vote_average|nm0005658': 0.9243363213059627,
 'others|vote_average|nm0371277': -0.054372724782703684,
 'others|vote_average|nm0106922': 1.6311817434811104,
 'others|vote_average|nm0376221': 0.21749089913081474,
 'others|vote_count|nm0005658': 1.3250739548242836,
 'others|vote_count|nm0371277': -0.6568418171478541,
 'others|vote_count|nm0106922': 1.547185205131506,
 'others|vote_count|nm0376221': 1.1029627045170614,
 'others|profit|nm0005658': 1.3245559575319341,
 'others|profit|nm0371277': -0.6967050973955428,
 'others|profit|nm0106922': 1.5509498843779983,
 'others|profit|nm0376221': 1.0981620306858697,
 'others|rev_budget_ratio|nm0005658': 1.3209992671259205,
 'others|rev_budget_ratio|nm0371277': -0.6125323549889363,
 'others|rev_budget_ratio|nm0106922': 1.5499151060998095,
 'others|rev_budget_ratio|nm0376221': 1.092083428152032,
 'prod_company|vote_average|Fox Film Corporation': -0.8728715609439692,
 'prod_company|vote_count|Fox Film Corporation': -0.5810710786331444,
 'prod_company|profit|Fox Film Corporation': -0.5607086271824212,
 'prod_company|rev_budget_ratio|Fox Film Corporation': -0.6627523812033179,
 'writer|vote_average|nm5921220': -0.16113278791308966,
 'writer|vote_average|nm0107543': 0.3544921334087972,
 'writer|vote_count|nm5921220': -0.7041071646051568,
 'writer|vote_count|nm0107543': -0.7020975829723201,
 'writer|profit|nm5921220': -0.6798656940452052,
 'writer|profit|nm0107543': -0.664030389376947,
 'writer|rev_budget_ratio|nm5921220': -0.7926906121881104,
 'writer|rev_budget_ratio|nm0107543': -0.7864407791410922,
 'director|vote_average|nm0107543': -0.8728715609439696,
 'director|vote_count|nm0107543': -0.5810710786331444,
 'director|profit|nm0107543': -0.5607086271824212,
 'director|rev_budget_ratio|nm0107543': -0.662752381203318,
 'cast|vote_average|nm0393411': -0.04938281206936502,
 'cast|vote_average|nm0445807': 0.6090546821888352,
 'cast|vote_average|nm0790137': 0.3895755174361018,
 'cast|vote_average|nm0208415': 0.1700963526833684,
 'cast|vote_count|nm0393411': -0.5542854573925757,
 'cast|vote_count|nm0445807': -0.5509371435296455,
 'cast|vote_count|nm0790137': -0.5520532481506223,
 'cast|vote_count|nm0208415': -0.553169352771599,
 'cast|profit|nm0393411': -0.5266554768593276,
 'cast|profit|nm0445807': -0.5003877141774293,
 'cast|profit|nm0790137': -0.5091436350713955,
 'cast|profit|nm0208415': -0.5178995559653615,
 'cast|rev_budget_ratio|nm0393411': -0.6201964982363489,
 'cast|rev_budget_ratio|nm0445807': -0.6099433348415453,
 'cast|rev_budget_ratio|nm0790137': -0.6133610559731465,
 'cast|rev_budget_ratio|nm0208415': -0.6167787771047477,
 'others|vote_average|nm0402478': -1.6311817434811104,
 'others|vote_average|nm0005646': -0.5437272478270369,
 'others|vote_average|nm0191667': -1.0874544956540737,
 'others|vote_average|nm1135428': 0.0,
 'others|vote_count|nm0402478': -0.6672829442990483,
 'others|vote_count|nm0005646': -0.6653845575442857,
 'others|vote_count|nm0191667': -0.666333750921667,
 'others|vote_count|nm1135428': -0.6644353641669044,
 'others|profit|nm0402478': -0.6604486910018728,
 'others|profit|nm0005646': -0.6454370644073665,
 'others|profit|nm0191667': -0.6529428777046196,
 'others|profit|nm1135428': -0.6379312511101133,
 'others|rev_budget_ratio|nm0402478': -0.7189946371552972,
 'others|rev_budget_ratio|nm0005646': -0.7132093095885026,
 'others|rev_budget_ratio|nm0191667': -0.7161019733719,
 'others|rev_budget_ratio|nm1135428': -0.7103166458051053}

In [223]:
total_scores

{'prod_company|vote_average': 7656.699999999997,
 'prod_company|vote_count': 3823522.0,
 'prod_company|profit': 194133282498.40308,
 'prod_company|rev_budget_ratio': 6824.201482889147,
 'writer|vote_average': 7259.199999999995,
 'writer|vote_count': 3827096.0,
 'writer|profit': 209676566513.2651,
 'writer|rev_budget_ratio': 6162.22247071716,
 'director|vote_average': 2056.1000000000004,
 'director|vote_count': 977297.0,
 'director|profit': 53256358779.31625,
 'director|rev_budget_ratio': 2284.732411645869,
 'cast|vote_average': 23133.999999999996,
 'cast|vote_count': 11533530.0,
 'cast|profit': 597606638159.3447,
 'cast|rev_budget_ratio': 26007.561910137778,
 'others|vote_average': 18933.49999999999,
 'others|vote_count': 7920238.0,
 'others|profit': 366087128275.8579,
 'others|rev_budget_ratio': 16916.720084839686}

In [222]:
individual_scores

{'prod_company|vote_average|Fox Searchlight Pictures': 79.1,
 'prod_company|vote_average|Van Brand': 18.0,
 'prod_company|vote_average|Metrol Technology': 4.9,
 'prod_company|vote_average|Trans-Radial Pictures': 26.8,
 'prod_company|vote_average|Good Universe': 14.4,
 'prod_company|vote_average|Seven Bucks Productions': 26.200000000000003,
 'prod_company|vote_average|Mission Films': 14.6,
 'prod_company|vote_average|Morgan Creek Productions': 32.0,
 'prod_company|vote_average|20th Century Fox Animation': 28.4,
 'prod_company|vote_average|Sony Pictures Animation': 39.8,
 'prod_company|vote_average|Latina Pictures': 20.1,
 'prod_company|vote_average|Skydance Media': 30.2,
 'prod_company|vote_average|The Safran Company': 19.5,
 'prod_company|vote_average|DC Comics': 31.0,
 'prod_company|vote_average|Atlas Entertainment': 35.4,
 'prod_company|vote_average|Mandeville Films': 48.6,
 'prod_company|vote_average|Acacia Filmed Entertainment': 14.8,
 'prod_company|vote_average|Vertigo Entertainment': 70.2,
 'prod_company|vote_average|Parkes+MacDonald Image Nation': 9.8,
 'prod_company|vote_average|Culture China - Image Nation Abu Dhabi Fund': 31.0,
 'prod_company|vote_average|Jon Shestack Productions': 28.0,
 'prod_company|vote_average|Cross Creek Pictures': 24.8,
 'prod_company|vote_average|Lantern Entertainment': 28.4,
 'prod_company|vote_average|Ram Bergman Productions': 21.0,
 'prod_company|vote_average|Decibel Films': 27.6,
 'prod_company|vote_average|Black Label Media': 28.4,
 'prod_company|vote_average|Head Gear Films': 19.6,
 'prod_company|vote_average|Lionsgate': 93.6,
 'prod_company|vote_average|Cruel & Unusual Films': 27.0,
 'prod_company|vote_average|Twisted Media': 29.0,
 'prod_company|vote_average|Omeira Studio Partners': 28.0,
 'prod_company|vote_average|3311 Productions': 18.0,
 'prod_company|vote_average|Redrover': 23.2,
 'prod_company|vote_average|Will Packer Productions': 34.0,
 'prod_company|vote_average|IAC Films': 36.5,
 'prod_company|vote_average|Playtone': 27.5,
 'prod_company|vote_average|Alloy Entertainment': 36.0,
 'prod_company|vote_average|Entertainment 360': 21.9,
 'prod_company|vote_average|Village Roadshow Pictures': 71.5,
 'prod_company|vote_average|RT Features': 33.2,
 'prod_company|vote_average|Savvy Media Holdings': 37.0,
 'prod_company|vote_average|Thunder Road Pictures': 65.1,
 'prod_company|vote_average|TriStar Pictures': 25.6,
 'prod_company|vote_average|Original Film': 27.6,
 'prod_company|vote_average|LStar Capital': 14.8,
 'prod_company|vote_average|Image Nation': 22.0,
 'prod_company|vote_average|ToonBox Entertainment': 17.4,
 'prod_company|vote_average|A24': 7.3,
 'prod_company|vote_average|Dune Entertainment': 36.5,
 'prod_company|vote_average|Feigco Entertainment': 21.2,
 'prod_company|vote_average|Matt Tolmach Productions': 26.8,
 'prod_company|vote_average|21 Laps Entertainment': 36.0,
 'prod_company|vote_average|Participant Media': 41.0,
 'prod_company|vote_average|Pixar': 74.5,
 'prod_company|vote_average|Southpaw Entertainment': 28.4,
 'prod_company|vote_average|Minds Eye Entertainment': 25.0,
 'prod_company|vote_average|M.Y.R.A. Entertainment': 16.6,
 'prod_company|vote_average|DreamWorks Pictures': 60.0,
 'prod_company|vote_average|Safehouse Pictures': 13.0,
 'prod_company|vote_average|Walt Disney Pictures': 189.1,
 'prod_company|vote_average|KatzSmith Productions': 7.2,
 'prod_company|vote_average|Columbia Pictures': 126.30000000000001,
 'prod_company|vote_average|Summit Entertainment': 35.5,
 'prod_company|vote_average|DreamWorks Animation': 62.0,
 'prod_company|vote_average|Uncharted': 30.5,
 'prod_company|vote_average|La CinÃ©facture': 41.5,
 'prod_company|vote_average|Illumination Entertainment': 25.2,
 'prod_company|vote_average|Bull Productions': 21.6,
 'prod_company|vote_average|Metro-Goldwyn-Mayer': 21.6,
 'prod_company|vote_average|Marvel Studios': 113.0,
 'prod_company|vote_average|Protozoa Pictures': 35.0,
 'prod_company|vote_average|The Fyzz Facility': 7.4,
 'prod_company|vote_average|Imperative Entertainment': 19.200000000000003,
 'prod_company|vote_average|Infinite Frameworks': 9.8,
 'prod_company|vote_average|XYZ Films': 24.5,
 'prod_company|vote_average|Dentsu': 19.3,
 'prod_company|vote_average|Waverly Films': 24.0,
 'prod_company|vote_average|Entertainment Studios Motion Pictures': 34.0,
 'prod_company|vote_average|Disruption Entertainment': 20.700000000000003,
 'prod_company|vote_average|Redwire Pictures': 14.399999999999999,
 'prod_company|vote_average|Nick Wechsler Productions': 12.6,
 'prod_company|vote_average|Free Association': 33.5,
 'prod_company|vote_average|Primate Pictures': 30.0,
 'prod_company|vote_average|Rabbit Bandini Productions': 28.8,
 'prod_company|vote_average|TIK Films': 31.5,
 'prod_company|vote_average|Dayday Films': 31.6,
 'prod_company|vote_average|Frenesy Film Company': 24.900000000000002,
 'prod_company|vote_average|Truenorth Productions': 7.0,
 'prod_company|vote_average|Gravier Productions': 32.0,
 'prod_company|vote_average|Reel Chefs Catering': 25.0,
 'prod_company|vote_average|Bron Studios': 18.6,
 'prod_company|vote_average|Alcon Entertainment': 29.0,
 'prod_company|vote_average|Blue Sky Studios': 35.5,
 'prod_company|vote_average|Radar Pictures': 33.5,
 'prod_company|vote_average|Cinereach': 22.200000000000003,
 'prod_company|vote_average|CBS Films': 18.9,
 'prod_company|vote_average|Formula Film': 14.0,
 'prod_company|vote_average|Actual Films': 27.2,
 'prod_company|vote_average|Killer Films': 21.0,
 'prod_company|vote_average|Michael De Luca Productions': 18.6,
 'prod_company|vote_average|Gulfstream Pictures': 29.0,
 'prod_company|vote_average|Voltage Pictures': 19.200000000000003,
 'prod_company|vote_average|Gerber Pictures': 5.0,
 'prod_company|vote_average|Chestnut Ridge': 37.0,
 'prod_company|vote_average|Fremantle Productions': 12.2,
 'prod_company|vote_average|Amblin Entertainment': 25.6,
 'prod_company|vote_average|Double Dare You Productions': 36.0,
 'prod_company|vote_average|Ad Hominem Enterprises': 25.5,
 'prod_company|vote_average|Paulilu Productions': 28.0,
 'prod_company|vote_average|Casadelic Pictures': 4.8,
 'prod_company|vote_average|Legendary Entertainment': 32.0,
 'prod_company|vote_average|Sidney Kimmel Entertainment': 37.5,
 'prod_company|vote_average|Netter Productions': 28.4,
 'prod_company|vote_average|Atomic Monster': 32.5,
 'prod_company|vote_average|Film 44': 22.200000000000003,
 'prod_company|vote_average|Monkeypaw Productions': 37.5,
 'prod_company|vote_average|Los Angeles Media Fund (LAMF)': 61.0,
 'prod_company|vote_average|Sony Pictures': 84.0,
 'prod_company|vote_average|Escape Artists': 35.5,
 'prod_company|vote_average|The Estate of Agatha Christie': 6.7,
 'prod_company|vote_average|Amazon Studios': 62.6,
 'prod_company|vote_average|Paramount': 91.8,
 'prod_company|vote_average|Fuji Television Network': 6.2,
 'prod_company|vote_average|Vesuvius Productions': 33.0,
 'prod_company|vote_average|Electric Entertainment': 5.8,
 'prod_company|vote_average|Rahaman Studios': 0.0,
 'prod_company|vote_average|Nine Stories Productions': 14.0,
 'prod_company|vote_average|Nvizage': 25.6,
 'prod_company|vote_average|DC Entertainment': 46.7,
 'prod_company|vote_average|First Light': 29.2,
 'prod_company|vote_average|Le Grisbi Productions': 20.4,
 'prod_company|vote_average|Cloud Eight Films': 20.700000000000003,
 'prod_company|vote_average|Perfect World Pictures': 65.39999999999999,
 'prod_company|vote_average|Infinitum Nihil': 19.799999999999997,
 'prod_company|vote_average|Riverstone Pictures': 17.4,
 'prod_company|vote_average|A Bigger Boat': 24.4,
 'prod_company|vote_average|Double Nickel Entertainment': 30.0,
 'prod_company|vote_average|Program Pictures': 25.6,
 'prod_company|vote_average|Lin Pictures': 14.4,
 'prod_company|vote_average|Genre Films': 44.6,
 'prod_company|vote_average|Warner Bros. Pictures': 75.7,
 'prod_company|vote_average|Arclight Films': 35.0,
 'prod_company|vote_average|Focus Features': 29.2,
 'prod_company|vote_average|FilmNation Entertainment': 103.0,
 'prod_company|vote_average|Dune Films': 19.200000000000003,
 'prod_company|vote_average|The Mark Gordon Company': 33.5,
 'prod_company|vote_average|Macari/Edelstein': 14.700000000000001,
 'prod_company|vote_average|Sailor Bear': 35.0,
 'prod_company|vote_average|Waypoint Entertainment': 27.2,
 'prod_company|vote_average|Saban Brands': 24.8,
 'prod_company|vote_average|An Independent Production': 0.0,
 'prod_company|vote_average|American Zoetrope': 22.8,
 'prod_company|vote_average|Davis Entertainment': 21.299999999999997,
 'prod_company|vote_average|Open Road Films': 58.2,
 'prod_company|vote_average|Annapurna Pictures': 78.8,
 'prod_company|vote_average|Tencent Pictures': 7.3,
 'prod_company|vote_average|Chazown Pictures': 34.5,
 'prod_company|vote_average|Memento Films International': 8.3,
 'prod_company|vote_average|De Line Pictures': 19.799999999999997,
 'prod_company|vote_average|Pascal Pictures': 22.200000000000003,
 'prod_company|vote_average|Big Indie Pictures': 7.0,
 'prod_company|vote_average|LuckyChap Entertainment': 30.0,
 'prod_company|vote_average|Scott Rudin Productions': 29.2,
 'prod_company|vote_average|Clubhouse Pictures': 37.5,
 'prod_company|vote_average|Story Ink': 30.0,
 'prod_company|vote_average|Imprint Entertainment': 19.2,
 'prod_company|vote_average|Wrigley Pictures': 30.0,
 'prod_company|vote_average|Di Bonaventura Pictures': 60.7,
 'prod_company|vote_average|VMI Worldwide': 20.0,
 'prod_company|vote_average|RatPac-Dune Entertainment': 86.60000000000001,
 'prod_company|vote_average|Intrepid Pictures': 20.4,
 'prod_company|vote_average|Endurance Media': 15.0,
 'prod_company|vote_average|The Weinstein Company': 21.299999999999997,
 'prod_company|vote_average|Stereo D': 23.2,
 'prod_company|vote_average|Ghoulardi Film Company': 36.5,
 'prod_company|vote_average|June Pictures': 14.8,
 'prod_company|vote_average|Grade A Entertainment': 39.5,
 'prod_company|vote_average|Lucasfilm': 35.0,
 'prod_company|vote_average|Reliance Entertainment': 21.0,
 'prod_company|vote_average|Buckeye Pictures': 21.2,
 'prod_company|vote_average|Gold Circle Films': 32.5,
 'prod_company|vote_average|Bold Films': 28.0,
 'prod_company|vote_average|Wigram Productions': 19.5,
 'prod_company|vote_average|Serendipity Productions': 18.299999999999997,
 'prod_company|vote_average|Black Bicycle Entertainment': 30.0,
 'prod_company|vote_average|Scott Free Productions': 86.3,
 'prod_company|vote_average|Blumhouse Productions': 56.4,
 'prod_company|vote_average|Bridgegate Pictures': 15.0,
 'prod_company|vote_average|Chernin Entertainment': 99.0,
 'prod_company|vote_average|Fibonacci Films': 14.0,
 'prod_company|vote_average|Cinelou Films': 22.0,
 'prod_company|vote_average|Jerry Bruckheimer Films': 26.4,
 'prod_company|vote_average|STX Entertainment': 79.1,
 'prod_company|vote_average|Awesomeness Films': 21.0,
 'prod_company|vote_average|Itaca Films': 28.8,
 'prod_company|vote_average|Weed Road Pictures': 26.0,
 'prod_company|vote_average|DiNovi Pictures': 27.5,
 'prod_company|vote_average|Apatow Productions': 22.200000000000003,
 'prod_company|vote_average|Freestyle Picture Company': 29.6,
 'prod_company|vote_average|Badhouse Studios Mexico': 19.2,
 'prod_company|vote_average|New Line Cinema': 141.2,
 'prod_company|vote_average|Zero Trans Fat Productions': 28.0,
 'prod_company|vote_average|FR Productions': 28.5,
 'prod_company|vote_average|Likely Story': 16.5,
 'prod_company|vote_average|Waddieish Claretrap': 4.9,
 'prod_company|vote_average|Universal Pictures': 143.70000000000002,
 'prod_company|vote_average|87Eleven': 28.4,
 'prod_company|vote_average|CondÃ© Nast Entertainment': 21.299999999999997,
 'prod_company|vote_average|Infinite Frameworks Studios': 14.700000000000001,
 'prod_company|vote_average|Kerner Entertainment Company': 31.0,
 'prod_company|vote_average|Jeff Rice Films': 9.6,
 'prod_company|vote_average|Digital Riot Media': 19.799999999999997,
 'prod_company|vote_average|Mister Lister Films': 26.0,
 'prod_company|vote_average|The Montecito Picture Company': 23.2,
 'prod_company|vote_average|Cre Film': 37.0,
 'prod_company|vote_average|Citizen Skull Productions': 28.0,
 'prod_company|vote_average|Hutch Parker Entertainment': 39.0,
 'prod_company|vote_average|Tyler Perry Studios': 28.0,
 'prod_company|vote_average|Marvel Entertainment': 15.6,
 'prod_company|vote_average|QC Entertainment': 55.0,
 'prod_company|vote_average|Huayi Brothers Media': 25.2,
 'prod_company|vote_average|Point Grey Pictures': 21.6,
 'prod_company|vote_average|Entertainment One': 10.0,
 'prod_company|vote_average|DMG Entertainment': 17.4,
 'prod_company|vote_average|Flynn Picture Company': 18.299999999999997,
 'prod_company|vote_average|China Film Co.': 13.8,
 'prod_company|vote_average|Parkside Pictures': 24.0,
 'prod_company|vote_average|Fuji Eight Company Ltd.': 20.700000000000003,
 'prod_company|vote_average|Mutiny Motion Pictures': 0.0,
 'prod_company|vote_average|TSG Entertainment': 75.80000000000001,
 'prod_company|vote_average|Broad Green Pictures': 35.9,
 'prod_company|vote_average|Psychopia Pictures': 24.0,
 'prod_company|vote_average|20th Century Fox': 208.5,
 'prod_company|vote_average|Twisted Pictures': 30.5,
 'prod_company|vote_count|Fox Searchlight Pictures': 41315.0,
 'prod_company|vote_count|Van Brand': 2259.0,
 'prod_company|vote_count|Metrol Technology': 522.0,
 'prod_company|vote_count|Trans-Radial Pictures': 7312.0,
 'prod_company|vote_count|Good Universe': 4184.0,
 'prod_company|vote_count|Seven Bucks Productions': 28716.0,
 'prod_company|vote_count|Mission Films': 8488.0,
 'prod_company|vote_count|Morgan Creek Productions': 3600.0,
 'prod_company|vote_count|20th Century Fox Animation': 6248.0,
 'prod_company|vote_count|Sony Pictures Animation': 8903.0,
 'prod_company|vote_count|Latina Pictures': 17574.0,
 'prod_company|vote_count|Skydance Media': 16257.0,
 'prod_company|vote_count|The Safran Company': 10407.0,
 'prod_company|vote_count|DC Comics': 40490.0,
 'prod_company|vote_count|Atlas Entertainment': 61730.0,
 'prod_company|vote_count|Mandeville Films': 48832.0,
 'prod_company|vote_count|Acacia Filmed Entertainment': 5352.0,
 'prod_company|vote_count|Vertigo Entertainment': 47893.0,
 'prod_company|vote_count|Parkes+MacDonald Image Nation': 3762.0,
 'prod_company|vote_count|Culture China - Image Nation Abu Dhabi Fund': 2760.0,
 'prod_company|vote_count|Jon Shestack Productions': 9352.0,
 'prod_company|vote_count|Cross Creek Pictures': 2208.0,
 'prod_company|vote_count|Lantern Entertainment': 1800.0,
 'prod_company|vote_count|Ram Bergman Productions': 27555.0,
 'prod_company|vote_count|Decibel Films': 4492.0,
 'prod_company|vote_count|Black Label Media': 2704.0,
 'prod_company|vote_count|Head Gear Films': 2088.0,
 'prod_company|vote_count|Lionsgate': 40438.0,
 'prod_company|vote_count|Cruel & Unusual Films': 43012.0,
 'prod_company|vote_count|Twisted Media': 12135.0,
 'prod_company|vote_count|Omeira Studio Partners': 2172.0,
 'prod_company|vote_count|3311 Productions': 1932.0,
 'prod_company|vote_count|Redrover': 908.0,
 'prod_company|vote_count|Will Packer Productions': 5060.0,
 'prod_company|vote_count|IAC Films': 21220.0,
 'prod_company|vote_count|Playtone': 14530.0,
 'prod_company|vote_count|Alloy Entertainment': 13240.0,
 'prod_company|vote_count|Entertainment 360': 12732.0,
 'prod_company|vote_count|Village Roadshow Pictures': 25758.0,
 'prod_company|vote_count|RT Features': 22308.0,
 'prod_company|vote_count|Savvy Media Holdings': 13380.0,
 'prod_company|vote_count|Thunder Road Pictures': 44369.0,
 'prod_company|vote_count|TriStar Pictures': 5176.0,
 'prod_company|vote_count|Original Film': 26704.0,
 'prod_company|vote_count|LStar Capital': 25830.0,
 'prod_company|vote_count|Image Nation': 11624.0,
 'prod_company|vote_count|ToonBox Entertainment': 681.0,
 'prod_company|vote_count|A24': 4244.0,
 'prod_company|vote_count|Dune Entertainment': 67040.0,
 'prod_company|vote_count|Feigco Entertainment': 2108.0,
 'prod_company|vote_count|Matt Tolmach Productions': 31428.0,
 'prod_company|vote_count|21 Laps Entertainment': 4082.0,
 'prod_company|vote_count|Participant Media': 3162.0,
 'prod_company|vote_count|Pixar': 63070.0,
 'prod_company|vote_count|Southpaw Entertainment': 6244.0,
 'prod_company|vote_count|Minds Eye Entertainment': 645.0,
 'prod_company|vote_count|M.Y.R.A. Entertainment': 11154.0,
 'prod_company|vote_count|DreamWorks Pictures': 11738.0,
 'prod_company|vote_count|Safehouse Pictures': 7070.0,
 'prod_company|vote_count|Walt Disney Pictures': 274710.0,
 'prod_company|vote_count|KatzSmith Productions': 12198.0,
 'prod_company|vote_count|Columbia Pictures': 101143.0,
 'prod_company|vote_count|Summit Entertainment': 4335.0,
 'prod_company|vote_count|DreamWorks Animation': 26090.0,
 'prod_company|vote_count|Uncharted': 25725.0,
 'prod_company|vote_count|La CinÃ©facture': 27885.0,
 'prod_company|vote_count|Illumination Entertainment': 17588.0,
 'prod_company|vote_count|Bull Productions': 23394.0,
 'prod_company|vote_count|Metro-Goldwyn-Mayer': 7944.0,
 'prod_company|vote_count|Marvel Studios': 194955.0,
 'prod_company|vote_count|Protozoa Pictures': 19150.0,
 'prod_company|vote_count|The Fyzz Facility': 2676.0,
 'prod_company|vote_count|Imperative Entertainment': 3882.0,
 'prod_company|vote_count|Infinite Frameworks': 1044.0,
 'prod_company|vote_count|XYZ Films': 2610.0,
 'prod_company|vote_count|Dentsu': 16096.0,
 'prod_company|vote_count|Waverly Films': 2964.0,
 'prod_company|vote_count|Entertainment Studios Motion Pictures': 5800.0,
 'prod_company|vote_count|Disruption Entertainment': 333.0,
 'prod_company|vote_count|Redwire Pictures': 633.0,
 'prod_company|vote_count|Nick Wechsler Productions': 3468.0,
 'prod_company|vote_count|Free Association': 9140.0,
 'prod_company|vote_count|Primate Pictures': 3550.0,
 'prod_company|vote_count|Rabbit Bandini Productions': 8368.0,
 'prod_company|vote_count|TIK Films': 8670.0,
 'prod_company|vote_count|Dayday Films': 9016.0,
 'prod_company|vote_count|Frenesy Film Company': 16731.0,
 'prod_company|vote_count|Truenorth Productions': 9185.0,
 'prod_company|vote_count|Gravier Productions': 3940.0,
 'prod_company|vote_count|Reel Chefs Catering': 515.0,
 'prod_company|vote_count|Bron Studios': 1656.0,
 'prod_company|vote_count|Alcon Entertainment': 1550.0,
 'prod_company|vote_count|Blue Sky Studios': 7810.0,
 'prod_company|vote_count|Radar Pictures': 39285.0,
 'prod_company|vote_count|Cinereach': 3732.0,
 'prod_company|vote_count|CBS Films': 5202.0,
 'prod_company|vote_count|Formula Film': 18370.0,
 'prod_company|vote_count|Actual Films': 344.0,
 'prod_company|vote_count|Killer Films': 1629.0,
 'prod_company|vote_count|Michael De Luca Productions': 14130.0,
 'prod_company|vote_count|Gulfstream Pictures': 1135.0,
 'prod_company|vote_count|Voltage Pictures': 2160.0,
 'prod_company|vote_count|Gerber Pictures': 103.0,
 'prod_company|vote_count|Chestnut Ridge': 1430.0,
 'prod_company|vote_count|Fremantle Productions': 10290.0,
 'prod_company|vote_count|Amblin Entertainment': 648.0,
 'prod_company|vote_count|Double Dare You Productions': 38990.0,
 'prod_company|vote_count|Ad Hominem Enterprises': 10155.0,
 'prod_company|vote_count|Paulilu Productions': 6085.0,
 'prod_company|vote_count|Casadelic Pictures': 211.0,
 'prod_company|vote_count|Legendary Entertainment': 32415.0,
 'prod_company|vote_count|Sidney Kimmel Entertainment': 3415.0,
 'prod_company|vote_count|Netter Productions': 3468.0,
 'prod_company|vote_count|Atomic Monster': 17345.0,
 'prod_company|vote_count|Film 44': 8028.0,
 'prod_company|vote_count|Monkeypaw Productions': 48035.0,
 'prod_company|vote_count|Los Angeles Media Fund (LAMF)': 11595.0,
 'prod_company|vote_count|Sony Pictures': 45581.0,
 'prod_company|vote_count|Escape Artists': 2250.0,
 'prod_company|vote_count|The Estate of Agatha Christie': 5858.0,
 'prod_company|vote_count|Amazon Studios': 10232.0,
 'prod_company|vote_count|Paramount': 36522.0,

In [ ]:
movies_encoded_no_redundant = movies_encoded.copy()

for col_type in nontrivial_col_types:
    for col in col_type: